src/server_kemal.cr
route.cr don't have logging and it's unfair to compare it Kemal which has logging on by default. This PR turns off Kemal's logging thus leads to more fair comparison. Also removed redundant status code
=> Turn off logging and remove redundant code

ruby/sinatra/Gemfile, ruby/sinatra/Gemfile.lock, ruby/sinatra/server_ruby_sinatra
The current Sinatra example uses Webrick for a web server and the development environment.
=> Fix Sinatra

Makefile
Add `--release` to shards build like Rust/Cargo
shards allow to append custom options to build command
https://github.com/crystal-lang/shards/blob/master/src/commands/build.cr#L33
=> Add release to shard build

node/express/app.js
the default hashing of the response and adding etag headers seems a bit too much.
=> disable etag generation in express

.env, crystal/kemal/Dockerfile, crystal/router.cr/Dockerfile, crystal/router.cr/src/server.cr, docker-compose.yml, ruby/rails/Dockerfile, ruby/roda/Dockerfile, ruby/sinatra/Dockerfile
Just simple setup to build containers and run them.
How to test it:
1. Install Docker https://docs.docker.com/engine/installation/
2. run `docker-compose up [server_name]`
3. try it with `curl http://localhost:3000/`
Cleanup:
1. Kill currently running server with `ctrl+c`
2. Remove all containers  and images with `docker-compose down`
PS: this is highly naive and if it should be meant seriously it needs a lot of improvement.
=> Ability to run crystal and ruby servers with Docker

Makefile, benchmarker/src/benchmarker.cr, node/express/bin/server_node_clusterexpress, node/express/cluster_express.js, node/express/package.json
usually (if memory and DB pools allows it) you run express in cluster, so it can utilize more than one core.
=> add cluster express

crystal/router.cr/src/server.cr
According to Crystal docs:
> A struct can also includes modules and can be generic, just like a class.
> 
> A struct is mostly used for performance reasons to avoid lots of small memory allocations when passing small copies might be more efficient.
> 
> So how do you choose between a struct and a class? The rule of thumb is that if no instance variable is ever reassigned, i.e. your type is immutable, you could use a struct, otherwise use a class.
https://crystal-lang.org/docs/syntax_and_semantics/structs.html
=> Use struct instead of class

README.md
"avg." is the most common abbreviation for "average"
=> Change abbreviation for "average"

Makefile, README.md, go/gin/main.go, neph.yml, tools/src/benchmarker.cr
Adds Go's Gin Web Framework, Linked to issue -> #81
=> Adds Go's Gin

tools/src/benchmarker.cr
Hi,
I can see a **wording** mistake (letter missing) when I run benchmarks.
Regards,
=> Missing 'n'

tools/src/benchmarker.cr
Hi,
Thread number are fixed **16**.
I could be useful to compute threads (for `http/client`) depending on (logical) cpu counts.
The purpose behind that is to run benchmark on multiple platforms.
Regards,
=> Dynamic calculation of benchmarking threads

Makefile
Hi, 
`Iris`, **go**, was missing from `Makefile`
=> Enable iris, while building with make

tools/src/benchmarker.cr
Hi,
In `PR` #111, I removed given thread number given to client.
`16` **threads** was created instead of  `core + 1`.
Regards,
=> Fix threads -> Dynamic calculation was wrong

Makefile, python/django/server_python_django, python/django/settings.py
Hi,
I think dependencies **SHOULD** be used in the last version (at least for interpreted languages).
This `PR` fix `django` -> it **SHOULD** whitelist local ip to run on **production** mode.
Regards,
=> Use the last (stable) version for each dependencies

Makefile
Hi,
[Lucky](https://luckyframework.org/) compilation fails due to static asset compilation, no need in our use case.
@paulcsmith How can we disable it ?
@tbrand This solution works but only using `make`, don't now about `neph`
Regards,
=> Fix lucky compilation

Makefile
Hi,
[Raze](https://github.com/samueleaton/raze) was missing when building with `make`.
Regards,
=> Enable raze (with make)

Makefile
Hi @tbrand,
To specify **production** `mode` usage, we **SHOULD** export environment variable.
I have set those, on `make`.
I don't know :
+ how to set for `neph`
+ if `router.cr` use such a feature
Regards,
This fix #138
=> Use production mode on Lucky / Raze / Kemal

python/django/settings.py
Hi,
**Django** was running on `production` mode, but calling ip was **blacklisted**.
Regards,
=> Fix django

python/tornado/requirements.txt
Hi,
In `tornado`, version was set to **4.5.3**.
However, for our use case (performance benchmarks) specifying version will disabled version update.
Regards,
=> Do not specify dependencies version

tools/src/benchmarker.cr
Hi @tbrand,
On https://github.com/tbrand/which_is_the_fastest/blob/6838408b4beb071c1f63b9e1f642b8456964aa08/tools/src/benchmarker.cr you've commented `django` and `flask`.
Was it voluntarily disabled ?
Regards,
=> Re-enable flask and django

neph.yaml, tools/src/benchmarker.cr
Hi,
[Rack-routing](https://github.com/iAmPlus/rack-routing) was enabled on `make`.
This `PR` enable it using `neph`
Regards,
=> Enable rack-routing via neph

neph.yaml, tools/src/benchmarker.cr
Hi,
I forget to add `rack-routing` to list of **ruby** frameworks to run on `neph`
Regards,
=> Add rack-routing

Makefile, neph.yaml, python/flask/server_python_flask
Hi
`Flask` run on **built-in** server => [Werkzeug](http://werkzeug.pocoo.org), no made for **production**.
This `PR` enable `gunicorn` for `flask`, as in `django`, @see #144 
Regards,
=> Run flask on gunicorn

crystal/spider-gazelle/.gitignore, crystal/spider-gazelle/.travis.yml, crystal/spider-gazelle/LICENSE, crystal/spider-gazelle/README.md, crystal/spider-gazelle/shard.yml, crystal/spider-gazelle/spec/spec_helper.cr, crystal/spider-gazelle/spec/welcome_spec.cr, crystal/spider-gazelle/src/app.cr, crystal/spider-gazelle/src/config.cr, crystal/spider-gazelle/src/controllers/application.cr, crystal/spider-gazelle/src/controllers/user.cr, crystal/spider-gazelle/src/controllers/welcome.cr
Please let me know if there is anything else I should do to add this framework.
I've started on documenting the project here too https://spider-gazelle.net/
Would love to see how it stacks up against the competition
=> [WIP] add spider-gazelle

ruby/rack-routing/Dockerfile, ruby/rails/Dockerfile, ruby/rails/config/puma.rb, ruby/roda/Dockerfile, ruby/sinatra/Dockerfile
Related to #69 
It starts many workers for each framework, I tested.
/cc @OvermindDL1
=> Make Ruby use all CPU cores (via Puma workers)

node/fastify/app.js
Fastify run on `127.0.0.1 ` by default, see https://github.com/fastify/fastify#example
Our `benchmark` require to listen on `0.0.0.0`
=> Fix fastify

nim/jester/Dockerfile, nim/mofuw/Dockerfile, nim/mofuw/server_nim_mofuw.nim
If "- d: release" is not used, it will be built in debug mode.
It has considerable overhead and performance gets worse.
I want you to redo the benchmark right now...
=> must use compile option "-d:release"

Makefile
To avoid **confusion**, `actix` targets has been renamed with `actix-web`.
:information_source: `Actix` is the general purpose **framework** and `actix-web` is the _web_ **framework** based on `actix`
=> Fix actix-web failure (make only)

rust/rocket/Dockerfile
Hi @SergioBenitez,
`Rocket` fails to compile on last **nightly** (from yesterday).
I have fixed compiler version.
Regards,
=> Fix rust version for rocket

.travis.yml, README.md, cpp/evhtp/Dockerfile, neph.yaml, tools/pipeline.lua, tools/pipeline_post.lua, tools/src/benchmarker.cr, tools/src/client.cr
Hi,
This `PR` enable `wrk`. Siege process is handled by `wrk` and a **custom** `lua` script, write results in a `csv` file.
The `crystal ` part parse the `csv` and compute the rank from the average latency.
I'm not quiet sure of how to define this rank (what metric should be in).
@OvermindDL1 Any idea ?
Regards,
=> Use wrk as a proper sieger

Makefile, neph.yaml, node/rayo/Dockerfile, node/rayo/app.js, node/rayo/package.json, tools/src/benchmarker.cr
Hi @aichholzer,
`Rayo` has dissapeared (my bad).
This `PR` re-enable it.
Regards,
=> Re-enable rayo

crystal/router.cr/src/server.cr
Hi,
`crystal` has changed (**braking change**) on `http/server`.
This implementation follow `0.25.0` and fix #257 
Regards,
=> Fix router.cr on latest crystal

.travis.yml, Makefile, neph.yaml, php/symfony/Dockerfile, php/symfony/composer.json, php/symfony/config/bundles.php, php/symfony/config/routes.yaml, php/symfony/public/index.php, php/symfony/src/Controller/ApplicationController.php, php/symfony/src/Kernel.php, tools/src/benchmarker.cr
Hi,
There is no **php** `frameworks` here. 
The reason was that in php world, there is not appserver (something bridging between php source and http), so we have to use :
+ php-fpm
+ nginx
So more works than with the other framework, that's why it take so long.
This `PR` add [symfony](https://github.com/symfony/symfony) as the first php framework
Regards,
=> Add symfony

python/japronto/requirements.txt
Hi,
`japronto` fails if `uvloop` `0.10.1` is used, @see #263 
This `PR` fix it by specify `0.8.1` version
Regards,
=> Downgrade uvloop (japronto)

rust/rocket/Dockerfile
hI,
`Rocket` fails to compile on **nightly**, so I've fixed the version.
@see https://github.com/rust-lang/rust/issues/51699
Regards,
=> Rocket compilation failure

Makefile, crystal/amber/shard.yml, crystal/lucky/src/actions/home/index.cr, tools/src/benchmarker.cr
Hi,
`Amber` has been disabled because of **braking change** in `crystal` `0.25.0`.
Thanks @faustinoaq and the awesome `Amber` community :tada: 
Regards,
=> Re-enable amber

Makefile, neph.yaml, ruby/hanami/Dockerfile, ruby/hanami/Gemfile, ruby/hanami/apps/web/controllers/home/index.rb, ruby/hanami/apps/web/controllers/home/register_user.rb, ruby/hanami/apps/web/controllers/home/user.rb, ruby/hanami/config.ru, ruby/hanami/config/boot.rb, ruby/hanami/config/environment.rb, tools/src/benchmarker.cr
Hi,
This `PR` add **hanami**
@see #140 
Regards,
=> Add hanami (ruby)

ruby/hanami/apps/web/controllers/home/user.rb
Hi,
This `PR` fix `hanami` implementation.
The controller behind `GET /user/:id` was not returning `:id` (**body** was not written)
Regards,
=> Fix hanami

Makefile, crystal/amber/config/environments/development.yml, crystal/amber/config/environments/production.yml, crystal/amber/config/environments/test.yml, crystal/amber/shard.yml, crystal/lucky/Dockerfile, crystal/raze/Dockerfile, crystal/raze/shard.yml, crystal/raze/src/server.cr, crystal/spider-gazelle/Dockerfile, crystal/spider-gazelle/shard.yml, neph.yaml, tools/src/benchmarker.cr
Hi,
`crystal` has been release in **0.26**.
This release introduce breaking changes, https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md#0261-2018-08-27
This `PR` upgrade `amber` since compatibility has been fixed by community
Thanks @robacarp and all `amber` **community** :tada:
Regards,
=> Use separated crystal version for each framework

.travis.yml
Hi,
Following the #340, this `PR` add `prism` to **CI**
Regards,
=> fix: forget to add prism on ci

python/japronto/requirements.txt
Hi,
This  `PR` upgrade `japronto` to **0.1.1** instead of using **master**
However, I need to fix `uvloop` to **0.8.1**, @see https://github.com/squeaky-pl/japronto/issues/122
Thanks @codenoid for your work :tada: 
Regards,
=> Use pypi version of japronto

scala/akkahttp/Dockerfile
I don't understand why `sbt run` is used though the uberjar is created via the `assembly` command.
=> scala/akkahttp: Running outside of sbt

tools/pipeline.lua, tools/pipeline_post.lua, tools/src/client.cr
Hi,
Benchmark results (`wrk` results) are written in file, and this one is parsed as CSV.
To simplify process, it will be convenient to use stderr (memory) to write this CSV.
Regards,
=> Use stderr instead of file

php/laravel/Dockerfile, php/symfony/Dockerfile
Hi,
`php` based framework could break the build process due to failure in `composer` installation.
Regards,
=> Fix php builds

dependencies.yml, node/koa/package.json, python/japronto/Dockerfile, python/japronto/server.py, tools/pipeline.lua, tools/pipeline_post.lua, tools/src/benchmarker.cr, tools/src/client.cr
Hi,
This `PR`  enable https://www.dependencies.io.
https://www.dependencies.io is an online service to manage dependencies.
Actually, configured for :
+ php
+ python
+ js
@OvermindDL1 As you mentionned once, it is easy to get out of sync if we use strict versions :stuck_out_tongue: 
This is a part of #357 
Regards,
=> Deps update

.travis.yml, FRAMEWORKS.yml, README.md, python/quart/Dockerfile, python/quart/requirements.txt
Hi,
This `PR` is a redo of #387.
`Quart` run now on `gunicorn` (`uvloop`).
Regards,
=> Optimize quart

FRAMEWORKS.yml
Hi @GNURub,
Thanks for your `PR` #389.
I think you **SHOULD** prefer website (for frameworks) as source code URLs.
Regards,
=> fix framework urls

tools/src/benchmarker.cr
Hi,
This `PR` disable by default display of **experimental** stuff in _results_
**experimental** stuff **COULD** be shown in `--experimental` flag is used
Regards,
=> Allow experimental stuff, but not display by default

FRAMEWORKS.yml, README.md
Hi,
[iron](http://ironframework.io) is shown as `0.7` in https://github.com/the-benchmarker/web-frameworks#full-table.
However, manifest is specifying  `0.6` 
https://github.com/the-benchmarker/web-frameworks/blob/master/rust/iron/Cargo.toml#L7
The official release is `0.6` https://crates.io/crates/iron
Regards,
=> Wrong version displayed for iron

.travis.yml, FRAMEWORKS.yml, nim/jester/Dockerfile, nim/jester/server_nim_jester.nimble
Hi @dom96,
`jester` was de-activated here.
This `PR` fix also #331
I also use `0.4.1` inspired by https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Nim/jester
Regards,
=> update jester to 0.4.1

FRAMEWORKS.yml
Hi,
`kitura` implementation was using `2.5.2`, but `2.2` was displayed on result table
This `PR` fix #405 
Regards,
=> wrong kitura version displayed

dependencies.yml
Hi,
This `PR` help us **NOT** getting out-of-sync with languages version (only for `development`)
On `development` (pined) docker instances are created, it defines language version
For example having
~~~dockerfile
FROM ruby:2.4
~~~
will show (in results) that ruby is in `2.4`
However, when the ruby `docker` image with `2.5` or `2.6` is out, we have to manually update it.
http://dependencies.io help us being warned about this update
Regards,
=> Follow docker images updates

crystal/amber/Dockerfile, crystal/amber/config/application.cr, crystal/amber/config/routes.cr, crystal/amber/src/amber.cr
This does several things to provide a better comparison:
- disable logging
- removes all unnecessary middleware
- enables port_reuse
- sets number of processes to 7 to leverage the 8 cores
This addresses issue #483
=> optimize amber

.travis.yml, FRAMEWORKS.yml, neph.yaml, rust/gotham/Cargo.toml, rust/gotham/Dockerfile, rust/gotham/src/main.rs, rust/iron/Cargo.toml, rust/iron/Dockerfile, rust/nickel/Cargo.toml, rust/nickel/Dockerfile, rust/rocket/Cargo.toml, rust/rocket/Dockerfile
~~~
export FRAMEWORK=gotham
shards install
crystal spec
~~~
This adds tests for Gotham, and makes sure all Rust images are aligned on the same build process (since Actix was previously using compiler optimizations that the other frameworks weren't). I can't get the tests to pass locally, but I think it's due to the state of my Docker (which I can't change, because I need it for something else). If someone could validate, I'd appreciate it.
=> Add Gotham benchmarks

FRAMEWORKS.yml, go/iris/Dockerfile, go/iris/go.mod, go/iris/main.go
Hi @kataras,
Thanks for sharing me the `+incompatible` hack in **go modules**, I honestly don't know what it does (not `golang` dev)
I have update the `iris`, fixing #503 
Regards,
=> update iris from 10 to 11

crystal/kemal/src/server.cr, python/aiohttp/requirements.txt, python/bottle/requirements.txt, python/cyclone/requirements.txt, python/django/requirements.txt, python/falcon/requirements.txt, python/flask/requirements.txt, python/japronto/requirements.txt, python/quart/requirements.txt, python/responder/Dockerfile, python/sanic/requirements.txt, python/starlette/requirements.txt, python/tornado/requirements.txt
Hi,
This `PR` specify strict versions of each dependencies for `python` **based** _frameworks_
This **COULD** be done because of http://pyup.io and it **COULD** avoid some side-effects
https://pyup.io/account/repos/github/the-benchmarker/web-frameworks/
Regards,
=> be more strict on python versionning

.ci/preflight.sh, go/chi/Dockerfile, go/gorilla-mux/Dockerfile
Hi,
This `PR` update `go` to the last minor
I've seen that all `go` **frameworks** does not use the same `go` `version`, this is now fixed :tada: 
Regards,
=> Upgrade golang

FRAMEWORKS.yml
Hi,
For `fastify` and `foxify` version of `node` in **results** was not the one in use
Regards,
=> fix node version in display

FRAMEWORKS.yml, go/fasthttprouter/go.mod, python/japronto/Dockerfile
Hi,
Since `uvloop` support `python` **3.7** (https://github.com/MagicStack/uvloop/releases/tag/v0.10.0), we can use this version for `japronto`
<hr>
~~~
export FRAMEWORK=japronto
shards install
crystal spec
~~~
=> use python 3.7 on japronto

python/tornado/Dockerfile, python/tornado/requirements.txt, python/tornado/server.py
Hi,
This `PR` aims to use `gunicorn` on top of `tornado` (instead of it own implementation)
The purpose is to make uniform all implementations (use `gunicorn` in the maximu of `python` **implementations**)
Addresses #720 
Regards,
=> Use gunicorn with tornado

renovate.json
Hi,
This `PR` disable `golang` on **renovate**
`renovate` remove `+incompatible` flag, @dependabot will replace it, thus
Addresses #764 
Regards,
=> disable renovate for golang

FRAMEWORKS.yml, go/chi/go.mod
Hi,
This `PR` upgrade `chi` to the next major
Major version are not updated by @dependabot on `golang`
Regards,
=> upgrade chi to 4.0

FRAMEWORKS.yml, README.md, rust/actix-web/Cargo.toml, rust/gotham/Cargo.toml, rust/iron/Cargo.toml, rust/nickel/Cargo.toml, rust/rocket/Cargo.toml
Hi @tomchristie,
I have seen that `starlette` has been updated to **0.9.1**, then it might fix my issue.
I also open this `PR` as a **central** point to re-enable :
+ starlette
+ responder
`here `
I'm working on `python` **3.7** 
The following :
~~~
shards install
shards build --release --no-debug
export FRAMEWORK=starlette
bin/neph ${FRAMEWORK} 
crystal spec
bin/benchmarker ${FRAMEWORK}
~~~
show that `starlette` is **OK** only when I comment lines https://github.com/the-benchmarker/web-frameworks/blob/master/tools/src/benchmarker.cr#L142-L152 wich lead to test only 1 endpoint (`/user` on `POST`)
=> Enable starlette / responder

FRAMEWORKS.yml, go/echo/go.mod, go/echo/main.go
Hi @alexaandru,
How can I use `echo` **4.0.0** using go modules ?
There is my `go.mod` file 
https://github.com/waghanza/http-benchmark/blob/upgrade_echo/go/echo/go.mod
Addresses #920
Regards,
=> Upgrade echo to 4x

.dependabot/config.yml, .travis.yml, FRAMEWORKS.yml, README.md, go/kami/Dockerfile, go/kami/go.mod, go/kami/main.go, neph.yaml
Hi @guregu,
This `PR` addresses #663
I've added `kami` in this benchmark.
Could you check our implementation ?
Results found (docker on 4 x CPU / 8gb)
| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| go (1.11) | [fasthttprouter](http://godoc.org/github.com/buaazp/fasthttprouter) (0.1) | 5.55 ms | 5.05 ms | 8.53 ms | 14.78 ms | 142.99 ms | 2863.00 | 
| go (1.11) | [chi](http://github.com/go-chi/chi) (4.0) | 13.00 ms | 9.39 ms | 21.24 ms | 118.09 ms | 427.88 ms | 21244.67 | 
| go (1.11) | …
=> Intoduce kami

FRAMEWORKS.yml
Hi,
This `PR` fix `roda` **version** show in `README`
Regards,
=> roda use 3.17 not 3.16

node/express/Dockerfile, node/fastify/Dockerfile, node/foxify/Dockerfile, node/hapi/Dockerfile, node/koa/Dockerfile, node/muneem/Dockerfile, node/polka/Dockerfile, node/rayo/Dockerfile, node/restana/Dockerfile, node/restify/Dockerfile, node/turbo_polka/Dockerfile
Hi,
This `PR` updates all `rust` implementations to use `node` `1.10.1`
Only for `docker` in **development**
Regards,
=> Upgrade node

rust/actix-web/Dockerfile, rust/gotham/Dockerfile, rust/iron/Dockerfile, rust/nickel/Dockerfile, rust/rocket/Dockerfile
Hi,
This `PR` updates all `rust` implementations to use `rust` `1.33`
Only for `docker` in **development**
Regards,
=> Update to rust 1.33

.travis.yml
Hi,
This `PR` fix travis builds.
Before : Only **master** was built
After : Only human branches (not containing **/**)
Regards,
=> surround travis regexp

FRAMEWORKS.yml, README.md, crystal/onyx/Dockerfile, crystal/onyx/shard.yml, crystal/onyx/src/server.cr
Onyx brings a lot of QoLs like request logging and CORS. However, enabling them makes the benchmarking results worse. Therefore, in the recent update I've added `BENCHMARK` build-time environment variable to enable benchmarking mode without logging and other neats.
=> Upgrade Onyx to 0.3.0

python/bottle/requirements.txt, python/django/requirements.txt, python/falcon/requirements.txt, python/flask/requirements.txt, python/hug/requirements.txt, python/molten/requirements.txt
Hi,
This `PR` `meinheld` for WSGI **servers**, from `0.6.1` to  `1.0.0`
@see https://github.com/mopemope/meinheld/blob/master/CHANGES.rst
Closes:
+ #1292
+ #1293
+ #1294
+ #1295
+ #1296
+ #1297
Regards,
=> [Python] Update meinheld to 1.0.1

nim/jester/Dockerfile, nim/jester/server_nim_jester.nimble
Hi,
This `PR` update to `nim` `0.19.6`.
It also update `jester` to the **latest** version.
Regards,
=> [Nim] Update to 0.19.6 in development

README.md, swift/kitura-nio/Dockerfile, swift/kitura/Dockerfile, swift/kitura/Package.swift, swift/perfect/Dockerfile, swift/vapor/Dockerfile
The Kitura Dockerfiles are based on ibmcom/swift-ubuntu images, which are (currently) built on Ubuntu 14.04.  There are performance penalties in this old version compared to recent releases - in particular a performance issue with libicu, which hurts Swift's string comparison performance.  In my local testing, Kitura performs ~35% faster on 18.04 compared to 14.04.
This PR replaces those with the official swift images (`swift:5.0.1` which is built on Ubuntu 18.04).  This makes for a fairer comparison with Vapor (which runs the same image), and Perfect (although this is running on `swift:4.2` which is 16.04-based).
I also updated the `kitura` version to 2.7, which seems like it was missed in #1320.
=> [Swift] Update Kitura Dockerfiles to Ubuntu 18.04

README.md, crystal/athena/Dockerfile, crystal/athena/athena.yml, crystal/athena/shard.yml, crystal/athena/src/server.cr, crystal/kemal/src/server.cr, crystal/orion/server.cr, crystal/raze/shard.yml, crystal/raze/src/server.cr, crystal/router.cr/src/server.cr
* kemal
* orion
* raze
* router.cr
(amber, onyx and spider-gazelle already have this, and it seems there is no easy method to set `reuse_port` argument for `HTTP::Server` in athena at the moment)
PS:
The [TechEmpower Framework Benchmarks (TFB)](https://github.com/TechEmpower/FrameworkBenchmarks) project uses a Bash script to fork processes for most web frameworks in Crystal:
* [amber](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/amber/run.sh)
* [crystal](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/crystal/run.sh)
* [crystal-radix](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/crystal/run-radix.sh)
* [h2o.cr](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks …
=> [Crystal] Parallel with processes for most in Crystal

.dependabot/config.yml, .travis.yml, FRAMEWORKS.yml, README.md, neph.yaml, node/0http/Dockerfile, node/0http/app.js, node/0http/package.json
Follow up for https://github.com/the-benchmarker/web-frameworks/issues/1098
`0http` is a low level HTTP routing server for Node.js equivalent to:
- fasthttprouter
- japronto
Faster than `restana`, it could set a good Node.js mark to beat.
=> [Javascript] Add 0http node.js framework

crystal/amber/config/application.cr, crystal/amber/src/amber.cr
The priority of the settings in `config/application.cr` does not seem to
be higher than the settings in `config/environments/*.yml`.
And the cluster mode of Amber is buggy at the moment. If the setting of
`process_count: 1` in `config/environments/*.yml` is changed to
`process_count: 4`, then the result is 8 sub-processes are forked.
The simplest workaroud at the moment is to fork `System.cpu_count`
sub-processes in `src/amber.cr`.
=> [Crystal] Temporarily fix multi-processing mode of Amber server

crystal/athena/Dockerfile, crystal/athena/athena.yml, crystal/athena/config.yaml
Sets the `ATHENA_ENV` to `test` to disable logging when running the benchmark.  This should regain some performance as logs would not be written to `STDOUT` or the `development.log` file.
=> [Crystal] Disable logging for athena benchmarking

.dependabot/config.yml, tools/src/make.cr
Hi,
This `PR` fix a misconfiguration for **dependabot** (on `JavaScript`).
Closes :
+ #1544 
+ #1545 
+ #1546 
+ #1547 
+ #1548 
+ #1549 
+ #1550 
+ #1551 
+ #1552 
+ #1553 
+ #1554 
+ #1555 
+ #1556 
Regards,
=> Wrong path for dependabot config file / node

rust/gotham/Cargo.toml, rust/gotham/config.yaml
Hi,
This  `PR` update `gotham` to **0.4**
I've used an `*` for `hyper` version, since `gotham` himself specify its version to use (I prefer to avoid double specifications)
Regards,
=> [Rust] Update gotham to 0.4

.dependabot/config.yml, .travis.yml, node/iotjs-express/Dockerfile, node/iotjs-express/app.js, node/iotjs-express/config.yaml, node/iotjs-express/package.json
This module is also supporting node runtime.
Another upcoming request would make sense to run app
on iotjs runtime (using supported docker image)
Relate-to: https://github.com/the-benchmarker/web-frameworks/issues/1643
Change-Id: I6ca293816b835d1b11345964162afb48565aca53
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> [Javascript] Add iotjs-express

nim/jester/server_nim_jester.nim, nim/jester/server_nim_jester.nim.cfg
- Improve code.
- Code Style.
- More Nim way of ding things.
:slightly_smiling_face:
=> [Nim] Improve code, Code Style, More Nim way

go/air/Dockerfile, go/atreugo/Dockerfile, go/beego/Dockerfile, go/chi/Dockerfile, go/echo/Dockerfile, go/fasthttprouter/Dockerfile, go/gf/Dockerfile, go/gin/Dockerfile, go/gorilla-mux/Dockerfile, go/goroute/Dockerfile, go/gorouter-fasthttp/Dockerfile, go/gorouter/Dockerfile, go/gramework/Dockerfile, go/kami/Dockerfile, go/rte/Dockerfile, go/violetear/Dockerfile
The default value of `GOPROXY` is `https://proxy.golang.org,direct` in `go1.13` version now so we don't need to set `GOPROXY` value.
=> [Go] Remove goproxy env

README.md, go/gf/go.mod
Hi,
This `PR` try to avoid the problem detected by @dependabot on https://github.com/the-benchmarker/web-frameworks/issues/1811
The fact was that `gf` has a failing dependency at version `1.9.3`
Regards,
---------------
Closes https://github.com/the-benchmarker/web-frameworks/issues/1811
---------------------
/cc @johngcn
=> [Go] Upgrade gf to 1.9.5

ruby/plezi/Dockerfile
When using `nproc` X 16 threads, there are 16 times the number of concurrent threads then there are processor cores.
This slows down the machine due to excessive lock contention and context switches. It only makes sense if most of the time the threads are "sleeping" or waiting on external IO (database requests).
For this simple plaintext test, a single thread would be better.
In fact, if I were to leave `nproc` behind, I would probably leave one CPU core available for OS tasks (`-w -1` would default to that state)... but maybe that could be tested across the board for everyone (by editing `nproc`).
=> [Ruby] Use a single thread for the server

.dependabot/mapping.yaml, tools/src/make.cr
Hi,
Several build tool could be used for a single language, for example in `java`, we can use :
+ `maven`
+ `gradle`
+ ...
This `PR` closes #1962, it is about enabling `gradle` for `java` based **frameworks.
Regards,
=> Enable multi manager manifests

.travis.yml
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
Hi, @waghanza. In previous PR i forgot adding nanoexpress and nanoexpress Pro to Travis CI and i think because of this results aren't changed. This PR should fix this
=> add nanoexpress (+pro) to travis

tools/src/db.cr
Hi @stakach,
This `PR` reorder (see next time I compute results), table by request per seconds.
As I've said in the linked issue, table could only show one criteria.
The project https://github.com/the-benchmarker/frontend will help with that, the idea is to have more graphs (for every aspect of _what we can call_ efficiency) instead of one big table
:heart: 
--------------------
Closes #2029
=> Sort results by requests (per second)

crystal/orion/config.yaml, crystal/orion/shard.yml
Hi @jwaldrip,
This `PR` update `orion` from `1.7` to `2.1`
I do not notice any change in `req/s`, from `124 639` to `124 292`
Do you maintain any changelog ?
Regards,
=> [Crystal] Update orion to 2.1

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
Hi @stakach,
This `PR` updates `spider-gazelle` to **2.2**
As you know we only show `requests/seconds`.
The gap between `2.1` and `2.2` is from **148 455** to **145 473** and show a decrease, but no very significant
Regards,
=> [Crystal] Update spider-gazelle to 2.2

nim/Dockerfile
Hi,
This `PR` update `nim` to `1.0.4`.
@dom96 @moigagoo Actually **nimlang/nim:1.0** in `docker`
I think it could be good, to have a **1.0** tag that link to the last patched version (`1.0.2`, `1.0.4` ...) in this **major**
Regards,
=> [Nim] Update containers to 1.04

python/sanic/server.py
this will turn off sanics access and debug logs, as per their documentation, which is supposed to be done in a production environment
=> turn off sanic debugging and access logging

go/fiber/config.yaml
It seems [gofiber.github.io/fiber](https://gofiber.github.io/fiber) has been changed to [fiber.wiki](https://fiber.wiki)
=> fix go/fiber's broken link

crystal/Dockerfile, crystal/config.yaml, tools/src/db.cr
Hi,
This `PR` update `crystal` to  `0.33` 
@see https://crystal-lang.org/2020/02/14/crystal-0.33.0-released.html
Regards,
---------------
Closes #2277, #2278
=> [Crystal] Upgrade to 0.33

javascript/nanoexpress/config.yaml, javascript/nanoexpress/package.json
Thanks to nanoexpress sponsors, we now can add [nanoexpress Pro](https://github.com/nanoexpress/pro) here too.
Within few month v2.0 will be released (currently available as [slim](https://github.com/nanoexpress/pro-slim) and unfinished) which has better performance, stability and less resource usage
=> chore(nanoexpress): update link

README.mustache.md
I think it was introduced during your rebase in https://github.com/the-benchmarker/web-frameworks/pull/2347.
=> Remove duplicated instructions

crystal/amber/config.yaml, crystal/amber/shard.yml
Hi,
This `PR` updates [amber](https://amberframework.org) to **0.34**.
Please notice that this version is compatible with `crystal` `>= 0.34`
Regards,
=> [Crystal] Update amber to 0.34

.ci/has_to_run.sh, .ci/template.mustache, .travis.yml
Hi,
This `PR` use _travis_terminate_ built-in function to exists unnecessary builds.
Builds are considered necessary, if :
+ from **master**
+ correspond to a modified **framework**
+ correspond to a modified **language**
Regards,
=> Avoid unnecessary builds

.ci/has_to_run.sh, fsharp/Dockerfile, fsharp/config.yaml
Hi @ademar,
I'm right to consider that running in a container based on `fsharp:10.7-netcore` use version `4.7` of fsharp ?
Regards,
------------
Closes #2473
=> [F#] Upgrade containers to 4.7

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
Hi,
This `PR` updates `spider-gazelle` to **2.4**
@stakach Does `spider-gazelle` version is driven by https://github.com/spider-gazelle/action-controller ?
Regards,
=> [Crystal] Update spider-gazelle to 2.4

elixir/cowboy/mix.exs, elixir/cowboy_stream/mix.exs, elixir/phoenix/mix.exs, elixir/plug/config.yaml, elixir/plug/mix.exs
Hi,
According to https://hexdocs.pm/elixir/Version.html, it is better to stick to `X.Y.Z` format to ensure parity of version displayed, and version used.
@esse Could you specify somethink in `mix.exs` to use *any* version of `plug_cowboy` in https://github.com/the-benchmarker/web-frameworks/blob/63422950ceba428840fca673fa93a9d73d90426a/elixir/plug/mix.exs#L32
/cc @essen @OvermindDL1 feel free to check `elixir` code `here` :heart: 
Regards,
=> [Elixir] Use X.Y.Z version

.ci/has_to_run.sh, .ci/template.mustache, .travis.yml, README.md, README.mustache.md, java/jooby/pom.xml, nim/httpbeast/config.yaml, spec/benchmark_spec.cr, tools/src/client.cr, tools/src/make.cr
Hi,
This `PR` adds `OSX` support
:warning: If you are not using a **linux** `distro`, you **MUST** :
+ have `docker-machine` (:information_source: available via `brew` for `OSX`)
+ use `bin/make config --driver docker-machine`
+ create a docker machine `docker-machine create the-benchmarker`
+ has a `DOCKER_HOST` defined `eval $(docker-machine env default)`
This is not the main `development workflow`, then any help maintaining `OSX` is :heart: 
------------------
Closes #2587
=> Add OSX support

renovate.json
Hi,
This  `PR` disable `renovate` for :
+ [x] php
+ [x] javascript
+ [x] elixir
The idea is that `dependabot` is working well enough for those languages.
-------------------------------
Closes #2553 #2570 #2610
=> Disable renovate for javascript, php, elixir

tools/src/db.cr, tools/src/make.cr
Hi,
As I have 8 cores, sieging uses 64,256,512,1024,2048 concurrency level.
Those level are based on my number of cores (`8^2`, `8^2*4`, `8^2*8`,`8^2*16`,`8^2*32`).
This `PR` fix `db` tool to get for this database the accurate concurrency level (it was previously **hard-coded**).
Regards,
=> Use dynamic concurrency level

clojure/Dockerfile, clojure/coast/config.yaml, java/Dockerfile, kotlin/Dockerfile
Hi,
This `PR` modify the default version for `jv` based frameworks :
+ [x] `clojure` => **11**
+ [x] `kotlin` => **11**
+ [x] `scala` => **11**
+ [x] `java` => **8** (since `act` use **8**, it is more accurate to use **8** for all `java` frameworks)
Regards,
---------
Closes #2638
=> [JVM] Use LTS version

clojure/luminus/project.clj
Hi,
This `PR` reverts #2654
With `muuntaja` `0.6.7`, I have a 
~~~java
Syntax error compiling new at (jsonista/core.clj:131:23).
Syntax error (ClassNotFoundException) compiling new at (jsonista/core.clj:131:23).
com.fasterxml.jackson.databind.ser.std.ToStringSerializerBase
~~~
/cc @yogthos
Regards,
=> Downgrade muuntaja to v0.6.6

pony/Dockerfile
Hi,
It convenient for maintenance tasks that `pony` compiles in one single binary.
It avoid having to setup third-party dependencies.
Regards,
=> [Pony] Use static compilation

go/chi/go.mod
Hi @pkieltyka,
This `PR` remove `+incompatible` flag for `chi`.
Seems to work without.
What is the impact @appleboy ?
Regards,
=> [Go] Remove incompatible flag fo chi

go/kami/go.mod
Hi @guregu,
As I understand https://github.com/renovatebot/renovate/issues/4586#issue-503006804 `// indirect` flags could not be updated `here`.
Moreover, having `+incompatible` appears not to be necessary.
Regards,
PS : Can I make you codeowner of `kami` here ? As this you will be pinged on each update
=> [Go] Remove extra flags for kami

README.md, csharp/aspnetcore/aspnetcore.csproj
C# ASP.NET Core was targeting `netcoreapp3.0` even though its config stated `3.1`. This PR updates the web app to `netcoreapp3.1`.
=> Update to netcoreapp3.1

python/apidaora/config.yaml
Hi @dutradda,
`apidaora` is failing `here`.
It appear that `maturin` require `rust` **nighlty**
https://github.com/racer-rust/racer/issues/1023 
Regards,
=> [Python] Use rust nightly to compile maturin

nim/Dockerfile
Hi,
As tag `1.2.2` is created in https://github.com/moigagoo/nimage, it will be shortly available in **docker hub** => https://hub.docker.com/r/nimlang/nim
Regards,
/cc @Willyboar
=> [Nim] Upgrade to 1.2.2

tools/src/make.cr
Hi @i4004,
Thanks for opening the issue #3028
The issue raised was due to a dynamic concurrency level selection. 
As I'm working on a 8 CPU, I have not the problem, but it seems that you have 12 CPU.
There is no need of a dynamic selection of currency levels, so I hard code it.
Let me know if this fix your bug
---
Closes  #3028
=> Hard-code concurrency levels

java/light-4j/pom.xml
Hi,
This `PR` removes (maven) plugin versions for java frameworks
+ [x] act
+ [x] blade
+ [x] javalin
+ [x] jooby
+ [x] light-4j
+ [x] micronaut
+ [x] rapidoid
+ [x] spring-boot
+ [x] spring-framework
+ [x] struts2
@tsuilouis @stevehu Is there any warning using this ?
Regards,
=> [Java] Remove maven plugin version

java/light-4j/config.yaml, java/light-4j/pom.xml
Hi @stevehu @tsuilouis,
This `PR` update https://github.com/networknt/light-4j to **2.0**
As I notice we have to compile targeted VM, right ?
Regards,
=> [Java] Update light4j to 2.0

php/simps/config/servers.php
Hi, @waghanza Can you test it for me?
=> Update config for simps

python/aiohttp/server.py, python/apidaora/server.py, python/asgineer/server.py, python/blacksheep/server.py, python/bottle/server.py, python/cherrypy/server.py, python/clastic/server.py, python/cyclone/server.py, python/django/app/wsgi.py, python/emmett/server.py, python/falcon/server.py, python/fastapi/server.py, python/flask/server.py, python/hug/server.py, python/klein/server.py, python/masonite/wsgi.py, python/molten/server.py, python/nameko/server.py, python/pyramid/server.py, python/quart/server.py, python/responder/server.py, python/sanic/server.py, python/starlette/server.py, python/tonberry/server.py, python/tornado/server.py
Hi,
This `PR` replace #3055. it **disable** logging for all `python` **frameworks**.
Logging is disabled for :
Regards,
/cc @pgjones @ahopkins @tiangolo @Ayehavgunne
=> [Python] Disable logging

renovate.json
Hi,
By default `renovatebot` does **NOT** upgrade `node` **major**
@see https://github.com/renovatebot/config-help/issues/791
This `PR` override this.
Regards,
=> [Javascript] Allow major upgrade for node

ruby/pakyow/Gemfile, ruby/pakyow/config.yaml
@waghanza This should fix the Pakyow issue that we discussed in https://github.com/the-benchmarker/web-frameworks/issues/3191. I realized that the benchmark app shouldn't even be using the `assets` framework since it doesn't rely on assets at all. Removing the `assets` framework was as easy as removing the metagem from `Gemfile`, which simply defines the standard gemset as a project dependency.
I also changed the command to boot in `ludicrous` mode, which configures the application for benchmarking.
Still can't get the benchmark to run for me locally, but it appears to be some other issue:
```
Successfully tagged ruby.pakyow:latest
[Error]  -- STDERR(.neph/ruby.pakyow/log/log.err) --
from ../../lib/db/src/db.cr:152:5 in 'build_database'
from ../../lib/db/src/db.cr:148:5 in …
```
=> Fix Pakyow, tune performance

java/javalin/config.yaml, java/jooby/config.yaml, java/rapidoid/config.yaml, java/spring-framework/config.yaml, java/struts2/config.yaml, kotlin/Dockerfile
Hi,
**-XX:+AggressiveOpts** has been deprecated in jdk `11` and is removed after
This `PR` remove it usage. It affects both `java` and `kotlin`
@see https://dzone.com/articles/jdk-13-what-is-aggressiveopts
Regards,
----------
Closes #3135
=> [Java/Kotlin] Remove AggressiveOpts

.travis.yml, javascript/fyrejet/app.js, javascript/fyrejet/config.yaml, javascript/fyrejet/package.json
This PR adds `Fyrejet`, a web-framework that is supposed to imitate Express APIs and provide greater performance.
I have basically copy-pasted the `express` `app.js` and only changed the `require()` statement to load `fyrejet` instead.
Unfortunately, I haven't been able to make `docker-machine` work properly on my `macOS Catalina` installation, so I haven't been able to check my PR properly.
=> [Javascript] Add fyrejet

.travis.yml, javascript/fyrejet-api/app.js, javascript/fyrejet-api/config.yaml, javascript/fyrejet-api/package.json, javascript/fyrejet-uwebsockets/app.js, javascript/fyrejet-uwebsockets/config.yaml, javascript/fyrejet-uwebsockets/package.json
I am not sure, whether this should be included, but the framework I created and added as part of #3322 supports [using uWebSockets.js](https://github.com/fyrejet/fyrejet#uwebsockets), as well as working [without Express's additions to `req` & `res`](https://github.com/fyrejet/fyrejet#special-routing-modes-). Therefore, I am sending this PR.
=> [Javascript] Add Fyrejet API mode & Fyrejet on uWebSockets.js

.travis.yml, r/httpuv/DESCRIPTION, r/httpuv/app.R, r/httpuv/config.yaml, r/plumber/DESCRIPTION, r/plumber/app.R, r/plumber/config.yaml, r/plumber/plumber.R
Fixes https://github.com/the-benchmarker/web-frameworks/issues/3303
Updates:
* Adds `r.plumber` framework
* Adds `r.httpuv` framework
---------------
Commands used to tests locally on macOS:
```bash
brew install crystal wrk postgresql docker-machine
/usr/local/opt/postgres/bin/createuser -s postgres
docker-machine rm default --force
docker-machine create default
eval $(docker-machine env default) 
shards build
bin/make config --driver docker-machine
export DATABASE_URL=postgresql://postgres@localhost/benchmark
dropdb -U postgres benchmark
createdb -U postgres benchmark
psql -U postgres -d benchmark < .ci/dump.sql
bin/neph r --seq 
bin/db to_readme
```
Relevant local test output:
|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) | …
=> Add R `plumber` and `httpuv`

go/Dockerfile, go/fiber/config.yaml, go/fiber/go.mod, go/fiber/main.go
Hi,
This `PR` fixes `fiber` **build**.
Due to https://github.com/gofiber/fiber/blob/fc10cbde9f8c46e2a2cc979256e1d6aadc4f689c/go.mod#L8, `fiber` requires a that `git` is available on build machine.
Regards,
-----------
Closes #3317
=> [Go] Update fiber to v2.0.2

fsharp/giraffe/Program.fs
The placement of ConfigureServices appears to have a negative impact on performance.
=> [FSharp] Update Giraffe sample

.github/workflows/ci.yml, lib/tasks/ci.rake
Hi,
It seems that github actions could run dynamic matrix
@see https://tomasvotruba.com/blog/2020/11/16/how-to-make-dynamic-matrix-in-github-actions/
This is required since full build takes ~1h30, using partial build could reduce CI time.
Regards,
/cc @leocavalcante
=> Use Github actions

javascript/low-http-server/app.js, javascript/low-http-server/config.yaml, javascript/low-http-server/package.json, reviewers.yaml
Adding [low-http-server](https://github.com/jkyberneees/low-http-server) HTTP server implementation. Here we are using `0http` as routing layer.
> This implementation is also based on uWebSockets!
=> adding low-http-server

java/struts2/pom.xml
Jetty v11 (JakartaEE Servlet API) is not supported by the Apache Struts 2.5.x yet.
=> Reverts Jetty version, v11 is not supported by Struts

php/Dockerfile, php/chubbyphp-workerman/config.yaml, php/workerman/config.yaml
Hi @walkor,
As I understand, it safer to use something like `libevent` when deploying `workerman` on **production**, right ?
Regards,
-------
Thanks for the tips @leocavalcante
=> [PHP] Use libevent for workerman

.github/workflows/ci.yml
Hi,
This `PR` adds a schedule (every monday) to run a full CI.
The idea is to ensure that all frameworks (last versions) are working correctly.
Regards,
=> Run CI regularly 

clojure/luminus/config.yaml, clojure/luminus/project.clj
Hi @yogthos,
This `PR` update luminus to 3.91.
Could you confirm that we are using 3.91 ?
Could also review this ? I do not know about clojure but `project.cjl` seems to list a lot of dependencies, shouldn't this deps handle by luminus-template ?
Regards,
------
Closes #3638 
------
Without `[com.fasterxml.jackson.core/jackson-core "2.12.0"]` I have a `com.fasterxml.jackson.core.util.JacksonFeature` at compile time
=> [Clojure] Update luminus to 3.91

php/fatfree/public/index.php
didn't see fat free in the results so I checked CI logs and noticed 500 returned by nginx 
I made a mistake in previous PR - I didnt move index.php into public dir
should be fine now
=> [FIX] fix php/fatfree index not being in the public dir

php/antidot/composer.json
Fix "antidot-framework/container" version. The added version was a tagging mistake. 
The 0.1.5 tag points to the 0.1.3 release that does not have support with PHP 8. I removed this tag and down the composer.json version to the correct one, the 0.1.4. 
Related to https://github.com/the-benchmarker/web-frameworks/pull/3655 thanks @waghanza ;- D
=> [PHP] antidot PHP8 support

rust/Dockerfile
I just noticed that you compile all rust frameworks for the `x86_64-unknown-linux-musl` target which is known to be much slower for most Rust programms due to something related to musl's allocator. Changing the target to debian, I saw performance uplift by factor 5 for the `rust/gotham` framework, which is probably more than what is caused by unpredictable Ryzen boosting behaviour:
**Before** (`alpine`)
```
benchmark=# select avg(value) from values where key_id = 3;
avg  
-------
90456
(1 row)
```
**After** (`debian:buster-slim`)
```
benchmark=# select avg(value) from values where key_id = 3;
avg   
--------
453782
(1 row)
```
=> Do not test Rust on musl

go/kami/go.mod
Hi,
`kami` could not compile will the latest version of go (at least **1.16**), all deps are not ready to use go modules, as I understand
https://the-benchmarker.semaphoreci.com/jobs/95b82f51-fae7-4a5a-9a73-74f6be6d6ace#L335
Regards,
=> [Go] Add incompatibility flag to kami

python/tornado/config.yaml, python/tornado/requirements.txt, python/tornado/server.py
Hi,
This `PR` switch from `gunicorn` worker to `tornado` _built-in_ server.
The idea is to use what frameworks are, and only rely of external lib if non is built-in (and suitable for **production**).
Same idea for `sanic`.
Regards,
@bdarnell Can you confirm the built-in server is **production** _ready_ ? What is your recommandation, if not ?
=> [Python] Use built-in server for tornado

haskell/servant/config.yaml, haskell/servant/server.cabal
Hi,
This `PR` updates https://github.com/haskell-servant/servant to **0.18**.
May I notify you on any update `here` that can affect https://github.com/haskell-servant/servant @jkarni @gdeest @phadej ?
Regards,
=> [Haskell] Update servant to 0.18

.tasks/collect.rake, pipeline.lua, pipeline_post.lua
From #4174, I noticed there are output typo on the `.json` file, metric label `minimim_latency` supposed to be `minimum_latency`. This PR fixes the typo.
=> fix typo minimim to minimum

php/antidot/config.yaml, php/chubbyphp-workerman/config.yaml, php/comet/config.yaml, php/driftphp/config.yaml, php/laravel-s-laravel/config.yaml, php/laravel-s-lumen/config.yaml, php/mark/config.yaml, php/nano/config.yaml, php/webman/config.yaml, php/workerman/config.yaml
Hi,
It appears that **posix** extension is already loaded by **pcnl**.
No need to use `docker-php-ext-install` in this case.
Regards,
=> [PHP] Duplicate posix extension load

swift/.gitignore, swift/Dockerfile
Optimization for all swift builds. Disables swift runtime memory exclusivity checks.
cc @0xTim 
Also added .gitignore for all swift builds
=> Swift disable runtime exclusivity checks

python/flask/config.yaml
See https://www.pocoo.org/. Flask is now hosted by palletsprojects.com
=> Fix website for Flask

php/swoole-coroutine/composer.json, php/swoole-coroutine/config.yaml, php/swoole/composer.json, php/swoole/config.yaml
This is not a real upgrade (since v4.7 is installed with `pecl install swoole`), more a fix / alignment with the doc
=> [PHP] Upgrade swoole to v4.7

php/antidot/composer.json, php/antidot/config.yaml
Hi @waghanza, I see that there is some issue running Antidot Framework inner the benchmark. 
I updated the composer.json file to get at least the minimum required versions.
Thanks for your great work and for maintaining this excellent project;-D
=> [PHP] Antidot: fix dependency issues in composer json

php/antidot/config.yaml, php/antidot/config/config.php, php/antidot/config/services/dependencies.prod.yaml
Hi @waghanza, after some research, I met that the allowed max concurrency were overloading PHP's memory since it breaks, I make some test locally and I look nice performance improvement by incrementing the PHP memory limit to 256M and by limiting the React-PHP HTTP server max concurrency to 512 requests.
Thanks again for your great work;-D.
=> [PHP] Antidot react: Fix max concurrency issues

javascript/fyrejet-uwebsockets/app.js, javascript/fyrejet-uwebsockets/package.json, javascript/fyrejet/app.js, javascript/sifrr/package.json
* Disables marketing `X-Powered-By` header
* Uses slightly faster version of `send` function to better showcase the underlying performance
* Updates uWebSockets.js
=> [javascript] Update benchmarks for fyrejet

php/chubbyphp-roadrunner/.rr.yaml, php/chubbyphp-roadrunner/composer.json, php/chubbyphp-roadrunner/config.yaml, php/chubbyphp-roadrunner/public/index.php, php/slim-roadrunner/.rr.yaml, php/slim-roadrunner/config.yaml, php/slim-roadrunner/public/index.php, php/sunrise-router-roadrunner/composer.json, php/sunrise-router-roadrunner/config.yaml
Hi,
The last version of `roarunner` is unusable on **alpine**
However, the previous version (**2.4**) works.
Regards,
=> [PHP] Use roadrunner 2.x

csharp/beetlex/config.yaml, csharp/beetlex/web.csproj
Hi @beetlex-io,
As I understand, `fasthttpapi` has been yanked. Thus we are facing an error **NU1605**
https://github.com/the-benchmarker/web-frameworks/runs/4753249621?check_suite_focus=true#step:6:59
Regards,
=> [C#] Fix BeetleX version

csharp/fastendpoints/Program.cs
default logging settings result in about a %95 performance drop when benchmarking.
=> [fastendpoints] disable logging providers

javascript/restana/config.yaml
This `PR` update [restana](https://github.com/BackendStack21/restana) website
@jkyberneees is it accurate to point on https://restana.21no.de instead of github ?
=> Update restana doc

javascript/hyper-express/app.js, javascript/hyper-express/config.yaml, javascript/hyper-express/package.json, reviewers.yaml
Hello, this is the PR to add HyperExpress support as discussed in issue #5319 
I simply initialized the HyperExpress application to serve requests on the 3 endpoints specified in the issue.
HyperExpress is built on top of uWebsockets.js like some other webservers hence I also included the following:
```yaml
build_deps:
- git # required by uWebSockets.js
bin_deps:
- gcompat # required by uWebSockets.js
```
------
Closes #5319
=> Added HyperExpress webserver

crystal/Dockerfile, crystal/athena/config.yaml, crystal/athena/shard.yml, crystal/athena/src/server.cr, nim/basolato/.gitignore
Had to add the ability for Crystal frameworks to add extra dependencies to the built image given Athena requires `pcre2` while the stdlib only uses `pcre1`.
I also added the generated Makefile and Dockerfile to `.gitignore` for a nim lang as it otherwise was being tracked.
=> Upgrade Athena to `0.17.x`

fsharp/giraffe-endpoints/Program.fs, fsharp/giraffe/Program.fs
This PR aims to further even the dotnet playing field by configuring [giraffe, giraffe-endpoints] with a common benchmark optimization for dotnet projects: removing Kestrel's server header.
* WebSharper - https://github.com/the-benchmarker/web-frameworks/blob/master/fsharp/websharper/Main.fs#L43 
* Falco - https://github.com/the-benchmarker/web-frameworks/blob/master/fsharp/falco/Program.fs#L25
This is a followup to https://github.com/the-benchmarker/web-frameworks/pull/5929
=> [fsharp][giraffe] Improve benchmark by configuring kestrel

fsharp/giraffe-endpoints/config.yaml, fsharp/giraffe-endpoints/web.fsproj, fsharp/giraffe/config.yaml, fsharp/giraffe/web.fsproj
Giraffe has been on its 6.0 release since mid 2022, so updating it here as well.
Giraffe repo: https://github.com/giraffe-fsharp/Giraffe 
Ran both locally with `dotnet run`
=> [FSharp][Giraffe / Giraffe-endpoints] Update giraffe to 6.0

fsharp/suave/Program.fs
I'm removing the default logger from Suave by using its built-in [Logger interface](https://github.com/SuaveIO/suave/blob/57d69e39e67a5b1a1c60b7c015c698a1901a9420/src/Suave/Utils/Logging.fs#L178) (see [docs](https://github.com/SuaveIO/suave/blob/57d69e39e67a5b1a1c60b7c015c698a1901a9420/docs/api.md))
I expect this to improve Suave's performance considerably and make this a better comparison against other fsharp frameworks.
* Problem: [I noticed that Suave was performing terribly](https://hamy.xyz/labs/2023-01-top-fsharp-backend-frameworks) - a negative outlier 
* It seems that Suave has default logging enabled when using the defaultConfig
* Solution: Remove logging
Note: I made [a similar PR to the Giraffe benchmark](https://github.com/the-benchmarker/web-frameworks/pull/5929) a few months …
=> [fsharp][suave] Remove logger IO in Suave to improve performance

javascript/bun.Dockerfile, javascript/config.yaml, javascript/elysia/app.ts, javascript/elysia/config.yaml, javascript/elysia/package.json, javascript/hono/app.ts, javascript/hono/config.yaml, javascript/hono/package.json, javascript/stricjs/app.ts, javascript/stricjs/config.yaml, javascript/stricjs/package.json
Add bun frameworks of elysia, stricjs and hono to the benchmark.
=> add elysia, stricjs and hono

crystal/amber/src/amber.cr, crystal/amber/src/controllers/application_controller.cr
- Removed the unnecessary explicit 'return'
- Changed from the deprecated `Process.fork` to `Process.exec` with a bit of recursiveness that should accomplish the same thing
=> Changed the deprecated `Process.fork` to the supported `Process.exec`

d/vibed/config.yaml, d/vibed/dub.json, d/vibed/dub.sdl, d/vibed/source/app.d, nim/Dockerfile, rust/actix/Cargo.toml, rust/axum/Cargo.toml, rust/gotham/Cargo.toml, rust/graphul/Cargo.toml, rust/iron/Cargo.toml, rust/nickel/Cargo.toml, rust/oxidy/Cargo.toml, rust/poem/Cargo.toml, rust/rocket/Cargo.toml, rust/salvo/Cargo.toml, rust/silent/Cargo.toml, rust/tide/Cargo.toml, rust/viz/Cargo.toml, rust/warp/Cargo.toml
As it was mentioned https://github.com/the-benchmarker/web-frameworks/issues/6374
Remove some potentially danger flags for production environment.
Not sure about the other flags. I suppose for real production even less flags could be used, but at least some bounds-check should be remain.
=> Production flags

crystal/amber/src/amber.cr
It now uses the 'app' binary name that the default docker file uses.
I still can't run this locally since I'm on an M1, which is a total bummer that Virtualbox doesn't work on M1 arch 😭
=> Updated the Amber test command 

javascript/hono/app.ts
Hi.
In this PR, I've changed the entry point of Hono app. Without the `reusePort: true` option, we get a duplicate port error when starting with pm2.
The errors:
When I run the `pm2 list` command, a process other than one fails:
I haven't tried this to see how much it affects performance, but it would fix the problem of forking. Thanks!
=> fix `Bun.serve` command for Hono

go/fiber/main.go, go/hertz/main.go
In `hertz` 0.7.2, the `disableDate` and `disableContentType` configuration options have been added.
This commit aims to bring hertz configuration closer to gofiber.
=> Aligning hertz configuration items with gofiber

java/armeria/src/main/java/benchmark/armeria/BenchmarkApplication.java
The default `ExchangeType` for `HttpService` is `BIDI_STREAMING` which is not optimized for non-streaming / simple requests. `UNARY` type is suitable for the current benchmark.
In fact, `ExchangeType` is automatically inferred for annotated service, gRPC, and Thrift services so normal users don't need to set the type explicitly.
=> Use `UNARY` type for Armeria `HttpService`

nim/Dockerfile, nim/guildenstern/server.nim.cfg, nim/httpbeast/server.nim.cfg, nim/mike/server.nim.cfg, nim/scorper/server.nim.cfg, nim/whip/server.nim.cfg
Hi @bung87 ,
After removing `thread:on`, `scorper` seems to perform better
```json
[
{
"level": 512,
"label": "minimum_latency",
"value": 3207.6666666666665,
"framework_id": 2
},
{
"level": 512,
"label": "total_requests_per_s",
"value": 2774.6666666666665,
"framework_id": 2
},
{
"level": 64,
"label": "duration_ms",
"value": 10017968.666666666,
"framework_id": 2
},
{
"level": 64,
"label": "percentile_75",
"value": 2143.3333333333335,
"framework_id": 2
},
{
"level": 512,
"label": "percentile_99",
"value": 77236.66666666667,
"framework_id": 2
},
{
"level": 512,
"label": "socket_connection_errors",
"value": 0,
"framework_id": 2
},
{
"level": 256,
"label": "average_latency",
"value": 6393,
"framework_id": 2
},
{
"level": 512,
"label": "socket_read_errors",
"value": 0,
"framework_id": 2
},
{ …
```
=> Remove thread compilation option

javascript/spliffy/package.json, javascript/spliffy/www/user/$id.rt.js
update spliffy to 1.2.1 
should fix failures seen on (not sure how to run the tests) https://github.com/the-benchmarker/web-frameworks/pull/7182
=> update to use new passthrough param instead of pathParameters

.tasks/ci.rake, javascript/bunicorn/app.ts, javascript/config.yaml
This `PR` remove `pm2` usage.
To be fair with `deno`, `node` and `bun`, maybe we should remove `pm2` clustering.
What do you think  @pi0 @qin-guan @dalisoft @jkyberneees @schamberg97 @kartikk221 @mcollina ?
Regards,
=> [Javascript] Clean-up clustering mode

crystal/marten/config/settings/base.cr
This pull request simply disables logging for the Marten server, as I suspect this is dragging results down a bit. I am seeing that most frameworks benchmarked in this repository use a similar strategy, so it also makes sense to follow a similar approach for Marten.
=> Disable logging for Marten

elixir/Dockerfile, elixir/cowboy/config.yaml, elixir/cowboy/mix.exs, elixir/cowboy_stream/config.yaml, elixir/cowboy_stream/mix.exs, elixir/phoenix_bandit/mix.exs, elixir/phoenix_cowboy/mix.exs, elixir/plug_bandit/mix.exs, elixir/plug_cowboy/mix.exs
The issue for all Elixir frameworks mentioned here https://github.com/the-benchmarker/web-frameworks/pull/7253 is probably due to mismatched versions of Debian for image `elixir:1.16` and `debian:bullseye` between build and runner images. I have fixed it by pinning the same version for the build and the runner image.
I have also updated all the packages.
=> Correct Debian version for Elixir frameworks

ruby/hanami/Gemfile
In #7260 and #7261, Renovate attempted to update the hanami and hanami-router gems to 2.1.0 _separately._
However, Hanami 2.1 requires these gems to be updated _together._
In this PR, I'm updating both gems, which should see the Hanami tests continue to pass.
Thanks for giving me a heads up, @waghanza!
=> Update to Hanami 2.1.0

python/django/app/views.py, python/django/settings.py
Django has a lot of stuff enabled by default which worsens performance significantly. It would be much more fair to disable them IMHO.
=> disable unused django apps and middlewares

d/serverino/dub.json, d/serverino/source/app.d
Can you try to run this code for full test please?
=> [D] Serverino debug/test

php/antidot/config.yaml
Hi waghanza,
I just updated Antidot framework dependencies to work with PHP 8.3. Sorry for the delay, but I hadn't realized it wasn't working. 
Thank you very much for your excellent work.
=> Add PHP 8.3 support

d/hunt/.gitignore, d/hunt/config.yaml, d/hunt/dub.json, d/hunt/source/app.d, d/serverino/dub.json, d/serverino/source/app.d, d/vibed/dub.json, d/vibed/source/app.d
This PR is adding new framework for D - Hunt http server.
I've also updated the worker pool size for serverino and vibe. Because larger pool sizes work better for me locally (but I've tested on macOS and M1). Hopefully it will improve the performance in Linux/Docker as well.
=> [D] Added Hunt and updated versions for serverino and vibe worker pool

go/nethttp/config.yaml, go/nethttp/go.mod, go/nethttp/main.go
=> Add go1.22 "net/http" package’s router

crystal/marten/config.yaml, crystal/marten/shard.yml
The [0.5 major version of Marten](https://martenframework.com/docs/the-marten-project/release-notes/0.5) was released yesterday. This pull request ensures that the Marten project used for this benchmark is set to use this latest major release.
=> [Crystal] Update Marten version to 0.5

crystal/athena/config.yaml, crystal/athena/shard.yml
Should resolve the failures as part of https://github.com/the-benchmarker/web-frameworks/pull/7615.
=> Upgrade `athena` to `0.19`

javascript/elysia/app.ts
This PR modifies Elysia code to use static resources by passing a value instead of a callback as recommended in [Elysia handler](https://elysiajs.com/essential/handler.html).
This allows Elysia to know data shape ahead of time allowing Elysia to optimize more performance.
Several plugins use this method eg, static plugins.
A static resource is not a cache as documented in [handler](https://elysiajs.com/essential/handler.html), as it can be mutated for each request or ignored/overridden by other lifecycle events.
=> feat(elysia): using static resource

ruby/rails-api/config/application.rb, ruby/rails-api/config/puma.rb, ruby/rails/config/application.rb, ruby/rails/config/puma.rb
The default value of puma threads has been [updated](https://edgeguides.rubyonrails.org/7_2_release_notes.html#set-a-new-default-for-the-puma-thread-count) in rails 7.2, now there are 3 of them.
=> chore(rails): update the number of puma threads to 3

ruby/config.yaml, ruby/rails-api/config.yaml, ruby/rails/config.yaml
Rails 7.2 enables YJIT itself after initialization.
This makes sure code that only runs on initializing is not jitted.
So for Rails we set RUBY_YJIT_ENABLE to falsey.
=> Enable YJIT for Ruby

ruby/Dockerfile
Using jemalloc typically reduces memory usage of a Ruby application:
https://www.speedshop.co/2017/12/04/malloc-doubles-ruby-memory.html
=> [ruby] Use Jemalloc for better memory performance

csharp/codebehind/HomeController.cs, csharp/codebehind/UserController.cs, csharp/codebehind/config.yaml, csharp/codebehind/web.csproj
We included a Regex function (to identify acceptable names for the class name) in order to pre-check the correctness of the requests; but we came to the conclusion that it is better to remove it, because the probability of such a situation is low.
https://github.com/elanatframework/Code_behind/commit/4f4c1141b0779f2c9d6c05e8118d244e354269f0
In new versions, answers are sent faster. We eagerly hope to have results close to "Minimal API" in ASP.NET Core.
=> Update CodeBehind Framework

java/spring-webflux/src/main/java/framework/benchmark/controller/BenchmarkController.java
Replaces the annotation-based controller with a functional routing approach. Introduces a `RouterFunction` bean to handle HTTP requests, eliminates redundant response creation, and improves efficiency by directly parsing path variables.
=> Refactor controller to use functional routing

javascript/express-bun/app.ts, javascript/express-bun/cluster.ts, javascript/express-bun/config.yaml, javascript/express-bun/package.json
`express-bun` added to the project as cluster.
=> Express bun added

zig/httpz/build.zig
@waghanza can you try compiling it again with binary stripping removed?
=> Remove binary stripping

csharp/genhttp/Program.cs, csharp/genhttp/config.yaml, csharp/genhttp/web.csproj, reviewers.yaml
Struggling a little bit with the documentation but this should probably work :)
=> [csharp] Add GenHTTP framework

php/config.yaml
According to the instructions [https://docs.roadrunner.dev/docs/general/compatibility#upgrading-to-roadrunner-v2024.1.x](https://docs.roadrunner.dev/docs/general/compatibility#upgrading-to-roadrunner-v2024.1.x) for the latest versions of roadrunner, it is recommended to use the `protobuf` PHP extension.
=> Adding the protobuf PHP extension for php/roadrunner

php/hleb2-workerman/app/Bootstrap/BaseContainer.php, php/hleb2-workerman/app/Bootstrap/ContainerFactory.php, php/hleb2-workerman/app/Bootstrap/ContainerInterface.php, php/hleb2-workerman/composer.json, php/hleb2-workerman/config.yaml, php/hleb2-workerman/config/common.php, php/hleb2-workerman/config/database.php, php/hleb2-workerman/config/main.php, php/hleb2-workerman/config/system.php, php/hleb2-workerman/console, php/hleb2-workerman/public/index.php, php/hleb2-workerman/routes/map.php
Added a new version of using the HLEB2 framework based on the [Workerman](https://www.workerman.net) web server.
=> [PHP]: hleb2-workerman added

fsharp/falco/Program.fs, fsharp/falco/config.yaml, fsharp/falco/web.fsproj
This PR updates Falco F# from version 3.1 to 5.0 and the dotnet runtime from version 8.0 to 9.0.
NuGet references will resolve to latest stable release of major versions. See: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#references-in-project-files-packagereference
=> 🐦 Falco v5.x

fsharp/Dockerfile, fsharp/config.yaml, fsharp/falco/web.fsproj, fsharp/frank/web.fsproj, fsharp/giraffe-endpoints/web.fsproj, fsharp/giraffe/web.fsproj, fsharp/saturn/web.fsproj, fsharp/suave/Program.fs, fsharp/suave/web.fsproj, fsharp/websharper/web.fsproj
I apologize, I didn't think to look at the other F# projects. I had just assumed they were already using net9.0.
This upgrade brings the full gamut up to the latest SDK, which should allow all the actions to pass. It looks like the test check last time died during the build phase because an older SDK was present. See: https://github.com/the-benchmarker/web-frameworks/actions/runs/13100015194/job/36547106181?pr=8203
=> f# upgrade to net9.0

rust/micro-web/Cargo.toml, rust/micro-web/config.yaml, rust/micro-web/src/main.rs
https://crates.io/crates/micro-web
A lightweight, modular web framework built on top of micro-http, providing an elegant and efficient way to build web applications in Rust.
=> feat: new framework "micro-web"

fsharp/frank/config.yaml, fsharp/frank/web.fsproj
I just recently updated Frank to have better support for net8.0 and net9.0. I've updated the sample to use the newer version 6.3.
=> feat(frank): update to Frank 6.3

javascript/bun/.gitignore, javascript/bun/bun.lock, javascript/bun/cluster.ts, javascript/bun/config.yaml, javascript/bun/package.json
Bun is not just a runtime, it is also a unified PM and development framework.
The unified Runtime and PM have been completed in Bun, and the Framework API has taken shape.
Therefore, we added Bun's server to the test❤️
> Also, I found that all the clustering code under javascript was implemented incorrectly.
=> feat: support Bun built-in http server

php/Dockerfile
A lot of PHP frameworks run from CLI, but the OPCache isn't enabled for CLI.
=> [php] Enable opcache with cli

php/workerman/start.php
And with better performance
ping @walkor
=> Simplify Workerman code

python/emmett/config.yaml, python/emmett/pyproject.toml
Specifically:
- use `uvloop`
- bump Python to 3.13
- remove legacy config
=> Fix emmett implementation

julia/http/Project.toml, julia/http/config.yaml, julia/http/deps.jl, julia/http/server.jl
Adds [JuliaWeb/HTTP.jl](https://github.com/JuliaWeb/HTTP.jl), based on https://github.com/the-benchmarker/web-frameworks/pull/8482
This will grab the latest HTTP.jl with major version 1 and minor version greater than 10, though note work is under way for version 2 at https://github.com/JuliaWeb/HTTP.jl/pull/1213. When that is merged the compat will need to be bumped.
Does the benchmark do any warmup requests? This is important to get good results in Julia since it is doing lazy compilation on the first requests.
=> Add Julia HTTP.jl

rust/khttp/src/main.rs
Changes the serving strategy for `khttp`.
`serve_epoll` was purely optimized for the use-case of only keep-alive connections (e.g. benchmarks), `serve` should have much better throughput if tcp connections are not reused.
=> khttp: use default serving strategy
