bin/server_ruby_roda, ruby/roda/Gemfile, ruby/roda/Gemfile.lock, ruby/roda/app.rb, ruby/roda/config.ru, ruby/roda/server_ruby_roda
=> Add roda example

Makefile, benchmarker/src/benchmarker.cr, bin/server_node_express, node/express/.gitignore, node/express/app.js, node/express/bin/server_node_express, node/express/package.json, ruby/rails/Gemfile.lock
I'v fixed https://github.com/tbrand/which_is_the_fastest/pull/11.
If @audy is ok, I'll merge this.
Thanks:smile:
=> Fix https://github.com/tbrand/which_is_the_fastest/pull/11

Makefile, go/fasthttprouter/main.go, neph.yml
Adding go [fasthttprouter](https://github.com/buaazp/fasthttprouter) to benchmarks.
=> fasthttprouter

Makefile, README.md, benchmarker/src/benchmarker.cr, neph.yml, swift/kitura/.gitignore, swift/kitura/Package.pins, swift/kitura/Package.swift, swift/kitura/Sources/main.swift, swift/perfect/.gitignore, swift/perfect/Package.pins, swift/perfect/Package.swift, swift/perfect/Sources/main.swift, swift/vapor/.gitignore, swift/vapor/Package.pins, swift/vapor/Package.swift, swift/vapor/Sources/main.swift
Hope you don't mind I just threw all three together into a single PR. Vapor, Perfect and Kitura. All build and run fine. 
I also added make and neph build targets and threw everything into the benchmarker as well.
=> Add Swift frameworks

rust/rocket/Cargo.lock, rust/rocket/src/main.rs
Pulling over @SergioBenitez's code from #26 (for easy one-click-merging^^) and updating Rocket's dependencies along the way.
=> Optimize rocket

Makefile, python/sanic/requirements.txt, python/sanic/server_python_sanic.py
=> add python/sanic server

benchmarker/src/benchmarker.cr
right now it's killing random processes that doesn't even relate to the benchmarking, or leaving things behind. (eg random node processes)
also it doesn't handle fx cluster express which launches multiple node processes.
this fixes both issues, and cleans up the code a lot.
=> bring some sanity to ExecServer.kill

benchmarker/src/benchmarker.cr
Reverts tbrand/which_is_the_fastest#40
=> Revert "Patch 2"

swift/perfect/Package.pins, swift/perfect/Package.swift
The Package.swift file for the Swift/Perfect app had the version locked to "2.0.x". I removed the minor version so that the newer packages will be utilized.
=> Perfect recent version

crystal/kemal/src/server.cr
=> Remove kemal static handler

crystal/kemal/shard.yml
I haven't release a new version but Kemal master has %10-15 performance boost.
=> Use Kemal master

csharp/aspnetcore/server_csharp_aspnetcore
The current code is running in debug mode (optimizations off)
=> Run aspnetcore in release mode

Makefile, README.md, neph.yml, python/flask/Dockerfile, python/flask/requirements.txt, python/flask/server_python_flask.py, tools/src/benchmarker.cr
=> Adds Python Flask

Makefile, README.md, neph.yml, nim/jester/Dockerfile, nim/jester/server_nim_jester.nim, nim/jester/server_nim_jester.nim.cfg, nim/jester/server_nim_jester.nimble, tools/src/benchmarker.cr
Not sure if there is something else needed to add a new language, but I think I have updated everything else.
=> Adds Nim's Jester

python/flask/server_python_flask.py, python/japronto/server_python_japronto.py, python/sanic/server_python_sanic.py, tools/src/benchmarker.cr
Hi,
`Flask` benchmarks has been **disabled**.
Inspecting source, I've understand *why* there is a `socket error ` on `flask`, it was running on `python` (**2.7**).
I've re-enable them.
Regards,
=> Re-enable flask

Makefile, README.md, ruby/rack-routing/.gitignore, ruby/rack-routing/Gemfile, ruby/rack-routing/Guardfile, ruby/rack-routing/README.md, ruby/rack-routing/app/app.rb, ruby/rack-routing/app/builder.rb, ruby/rack-routing/app/init.rb, ruby/rack-routing/app/request.rb, ruby/rack-routing/app/route_handler.rb, ruby/rack-routing/config.ru, ruby/rack-routing/config/routes.txt, ruby/rack-routing/server_ruby_rack-routing, ruby/rack-routing/spec/request_spec.rb, ruby/rack-routing/spec/spec_helper.rb, tools/src/benchmarker.cr
I was able to get it to work with `bin/server_ruby_rack-routing` and `time bin/client`. 
`bin/benchmarker` wasn't working on my system...
=> Add rack-routing

Makefile, crystal/spider-gazelle/src/controllers/user.cr, neph.yaml, tools/src/benchmarker.cr
Hi,
Enable [Spider gazelle](https://github.com/spider-gazelle) when **building** with
+ `neph`
+ `make`
Regards,
=> Add spider-gazelle in benchmark list

Makefile, crystal/spider-gazelle/.gitignore, crystal/spider-gazelle/.travis.yml, crystal/spider-gazelle/LICENSE, crystal/spider-gazelle/README.md, crystal/spider-gazelle/shard.yml, crystal/spider-gazelle/spec/spec_helper.cr, crystal/spider-gazelle/spec/welcome_spec.cr, crystal/spider-gazelle/src/app.cr, crystal/spider-gazelle/src/config.cr, crystal/spider-gazelle/src/controllers/application.cr, crystal/spider-gazelle/src/controllers/user.cr, crystal/spider-gazelle/src/controllers/welcome.cr, neph.yaml, node/express/bin/server_node_clusterexpress, node/express/bin/server_node_express, node/polka/bin/server_node_clusterpolka, node/polka/bin/server_node_polka, tools/src/benchmarker.cr
Hi,
It appears that  `node` **frameworks** where running on  `default` mode -> **development**.
This `PR` turn it into **production** mode
> DISCLAIMER : I don't know what are the differences in `node` word :stuck_out_tongue: 
Regards,
PS : Work in progress ... do not merge
=> [WIP] Use production mode

.travis.yml, shard.yml, tools/src/benchmarker.cr
Hi,
This `PR` enable CI. 
It is **irrelevant** to _run_ benchmarks on it, **CI** will help testing / maintaining 
@tbrand Could you activate `Travis` for this repository ?
Regards,
=> Use a CI service

tools/src/client.cr
Hi,
This `PR` allow to customize **hostname** (or **ip** address) to test when running `bin/client`
Regards,
=> Customize host to test

Makefile, neph.yaml
Hopefully this improves Jester's results :)
=> Compile Jester in release mode

neph.yaml, node/express/Dockerfile, node/express/package.json, node/fastify/Dockerfile, node/fastify/package.json, node/polka/Dockerfile, node/polka/package.json
Hi,
This `PR` lets `node` **apps**
+ express
+ fastify
+ polka
run using `pm2`
=> Clusterify node

node/express/Dockerfile, node/fastify/Dockerfile, node/polka/Dockerfile
Hi,
This `PR` enable to spread on all cores on `node`, using `-i` on `pm2`.
The rule : One worker per core
Regards,
=> Use all cores on node

Makefile, README.md, docker-compose.yml, neph.yaml, ruby/flame/.gitignore, ruby/flame/Dockerfile, ruby/flame/Gemfile, ruby/flame/application.rb, ruby/flame/config.ru, ruby/flame/controllers/index_controller.rb, ruby/flame/controllers/user_controller.rb, tools/src/benchmarker.cr
=> Add Flame (Ruby)

.travis.yml, test.sh
Hi,
In order to help maintenance of this project, I have create a little bash script to ensure all frameworks are fitting our rules.
Please feel free to contribute :heart: 
Regards,
PS : It will be re-written in  `crystal` later
PSS : It take approx. 1hour to validate all benchmarks on `travis-ci`
=> Add (basic) test

Makefile, tools/src/benchmarker.cr
Hi @aichholzer,
`Rayo` is amazing, I think I was too enthusiastic to merge it.
I remove it from **master**, but we will come back :stuck_out_tongue_closed_eyes: 
Regards,
=> Remove rayo

.travis.yml, neph.yaml, shard.yml
Hi,
`crystal` `0.25.0` introduce a **breaking change** in `yaml` api.
This `PR` fix it by using the latest version of `neph`.
Regards,
=> Upgrade to latest crystal

rust/rocket/Dockerfile
Hi,
This `PR` change for `rust` **nightly** on rocket.
Regards,
=> Fix rocket compilation

crystal/lucky/Dockerfile, crystal/lucky/config/route_helper.cr, crystal/lucky/shard.yml, crystal/lucky/src/actions/home/index.cr, crystal/lucky/src/server.cr
Hi,
`lucky` fails to compile on `crystal` **0.24.2**
Regards,
=> Upgrade lucky

Makefile, neph.yaml, node/restify/Dockerfile, node/restify/app.js, node/restify/package.json
Hi,
This `PR` add **restify**
@see #232 
Regards,
=> Add restify (node)

CONTRIBUTING.md, README.md
Hi,
This project is not not yet stable, but we are not far from it.
I think it is time to attract developers to add more **frameworks**.
Here is a step forward in this purpose.
Regards,
=> Clarify readme

python/django/Dockerfile, python/django/requirements.txt, python/flask/Dockerfile, python/flask/requirements.txt, python/flask/server.py, python/japronto/server.py, python/sanic/Dockerfile, python/sanic/requirements.txt, python/sanic/server.py, python/tornado/Dockerfile, python/tornado/requirements.txt, python/tornado/server.py
Hi,
This `PR` let `python` implementations use `gunicorn` for :
+ django
+ tornado
+ flask
+ sanic
:warning: Missing `japronto`
Regards,
=> Standardize python implementation

Makefile, neph.yaml, python/django/Dockerfile, python/django/requirements.txt, python/flask/Dockerfile, python/flask/requirements.txt, python/flask/server.py, python/sanic/Dockerfile, python/sanic/requirements.txt, python/sanic/server.py, python/tornado/server.py, python/vibora/Dockerfile, python/vibora/requirements.txt, python/vibora/server.py, tools/src/benchmarker.cr
I can't give any assurances about the code. I just tested it but, the `SO_REUSEPORT` is causing trouble, but wanted contribute anyway. That's why I've mentioned Introducing not Adding.
Partially solves #282 
If you guys can solve it, please do let me know.
edit: idk how to add the target to readme file, because they have already been ranked, therefore didn't know where to put the name in readme.md. also benchmarker.cr is in `tools/src/benchmarker.cr` not in `benchmarker/benchmarker.cr` as mentioned in the readme. 
Peace.
=> Introducing Vibora

nim/jester/Dockerfile, nim/jester/server_nim_jester.nim.cfg, nim/jester/server_nim_jester.nimble
Hi,
This `PR` fix `jester`.
This a temporary patch, since jester latest is now incompatible with nim (I use a specific commit).
@see #296 
Regards,
=> fix jester

python/vibora/server.py
Hi,
Following #302, this `PR` fix `vibora`.
@see https://docs.vibora.io/routing
Regards,
=> Fix vibora

Makefile, neph.yaml, node/hapi/Dockerfile, node/hapi/app.js, node/hapi/package.json, tools/src/benchmarker.cr
Hi,
As @armand1m pointed in #233 , `hapijs` has been dropped.
This `PR` restore it.
Regards,
=> Restore hapijs

crystal/spider-gazelle/Dockerfile, crystal/spider-gazelle/shard.yml, crystal/spider-gazelle/src/app.cr
Uses the latest version of crystal lang and spider-gazelle
=> Upgrade spider-gazelle

crystal/prism/Dockerfile, crystal/prism/server.cr, crystal/prism/shard.yml, neph.yaml, tools/src/benchmarker.cr
Hi,
This `PR` introduce `prism, following #184
@vladfaust I've taken inspiration from https://github.com/vladfaust/crystalworld/blob/master/src/bin/server.cr
Some results 
| Language (Runtime)        | Framework (Middleware)    |         Average |  50% percentile |  90% percentile |  99% percentile | 99.9% percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| crystal                   | spider-gazelle            | 6.98 ms | 5.98 ms | 12.26 ms | 20.77 ms | 48.21 ms | 4105.67 | 
| crystal                   | raze                      | 31.05 ms | 28.13 ms | 39.75 ms | 48.96 ms | 397.41 ms | 12629.00 | 
| crystal                   | prism …
=> Introduce prism

tools/src/benchmarker.cr, tools/src/client.cr
Hi,
This `PR` is a new one created from https://github.com/the-benchmarker/web-frameworks/pull/327
@tbrand I had to open this new one, to avoid conflicts (**github** wants to solve conflict since `PR` was opened long time ago)
Regards,
=> Show a simple ranking

.travis.yml, neph.yaml, shard.yml
I've fixed the broken neph configuration.
I just make it works but I'll add few functions after merging this.
For example, specifying multiple jobs.
=> Update nephp to 0.2.6

php/laravel/composer.json
Hi,
This `PR` update **laravel** to the **latest** version
Regards,
=> Update to laravel 5.7

python/flask/requirements.txt
Hi,
This `PR` update **gunicorn** on **flask** to the **latest** version
Regards,
=> Update gunicorn to 19.9

python/sanic/requirements.txt
Hi,
This `PR` update **sanic** to the **latest** version
Regards,
=> Update sanic to 0.8

python/django/requirements.txt
Hi,
This `PR` update **django** to the **latest** version
Regards,
=> Update django to 2.1

node/polka/package.json
Hi,
This `PR` update **polka** to the **latest** version
Regards,
=> Update to polka 0.4

go/echo/Dockerfile, go/fasthttprouter/Dockerfile, go/gin/Dockerfile, go/gorilla-mux/Dockerfile, go/iris/Dockerfile
* echo@v3.3.6
* gin@v1.3.0
* mux@v1.6.2
* iris@v10.7.0
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> update go framework version.

CODE_OF_CONDUCT.md, python/bottle/server.py, python/flask/server.py
Addresses: https://github.com/the-benchmarker/web-frameworks/issues/345
=> Code of conduct

.travis.yml, FRAMEWORKS.yml, PULL_REQUEST_TEMPLATE.md, c/kore/Dockerfile, c/kore/hello/.gitignore, c/kore/hello/conf/build.conf, c/kore/hello/conf/hello.conf, c/kore/hello/src/hello.c, neph.yaml
Hi,
Following #415, it is useful to have a `PR` template to list task to do before merging.
Regards,
=> PR template

FRAMEWORKS.yml
Hi,
This `PR` fix version for kore, fix https://github.com/the-benchmarker/web-frameworks/pull/449
`kore` use C99
Regards,
=> Fix kore build

.travis.yml, neph.yaml, php/symfony/config/packages/framework.yaml, php/symfony/config/routes.yaml, shard.yml
Reverts the-benchmarker/web-frameworks#492
Hi @tbrand,
My build process run successfully (on a `droplet`) with the commit just before upgrade
edafa4b20570930fb6b9a415d046e0595ac43632
I prefer revert this change, and leave **master** stable.
I'll investigate later.
BTW, thanks for contribution / neph upgrade
=> Revert neph upgrade

.travis.yml, FRAMEWORKS.yml, go/chi/Dockerfile, go/chi/go.mod, go/chi/main.go, neph.yaml
Hi,
This `PR` fix #515 
+ [x]  Configuration files
Regards,
=> Introduce chi

go/beego/Dockerfile, go/beego/go.mod, go/echo/Dockerfile, go/echo/go.mod, go/fasthttprouter/Dockerfile, go/fasthttprouter/go.mod, go/gin/Dockerfile, go/gin/go.mod, go/gorilla-mux/Dockerfile, go/gorilla-mux/go.mod, go/muxie/Dockerfile, go/muxie/go.mod
Hi @appleboy,
I've followed you advice and use [go modules](https://github.com/golang/go/wiki/Modules)
@kataras I have not been successful in using  [go modules](https://github.com/golang/go/wiki/Modules) in `iris` (when doing so `iris` require `blackfriday). any ideas ?
Regards,
=> Switch to go modules

swift/kitura/Package.swift, swift/perfect/Package.swift, swift/vapor/Package.swift
Hi @LoganWright @tanner0101,
I've updated `vapor` on this benchmarking project, this fix #534 
Could you do a quick review ?
Regards,
=> upgrade vapor from 3.0 to 3.1

go/chi/main.go, go/echo/main.go, go/gin/main.go
Hi,
`chi` implementation introduce a redundancy.
Regards,
=> Remove redundant code

.travis.yml, FRAMEWORKS.yml, neph.yaml, python/falcon/Dockerfile, python/falcon/requirements.txt, python/falcon/server.py
Hi,
This `PR` introduce [falcon](http://falcon.readthedocs.io), related to #539 
~~~
export FRAMEWORK=falcon
shards install
crystal spec
~~~
@kgriffs  Can you do a quick review on this code ?
Regards,
=> Introduce falcon

.travis.yml, FRAMEWORKS.yml, neph.yaml, python/starlette/Dockerfile, python/starlette/requirements.txt, python/starlette/server.py
+ [ ] Please check configuration files
closes #546 
@waghanza review this please. 
@tomchristie can you have a look, if everything has been implemented the way it is supposed to?
=> adding starlette

.travis.yml, FRAMEWORKS.yml, dependencies.yml, neph.yaml, ruby/agoo/Dockerfile, ruby/agoo/Gemfile, ruby/agoo/app.rb
~~~
shards install
crystal spec
~~~
=> Add Agoo framework

FRAMEWORKS.yml, crystal/router.cr/Dockerfile, crystal/router.cr/shard.yml
See: https://github.com/tbrand/router.cr/pull/29
=> update router.cr for improved performance

.travis.yml, FRAMEWORKS.yml, crystal/amber/Dockerfile, crystal/amber/shard.yml, crystal/kemal/Dockerfile, crystal/kemal/shard.yml, crystal/lucky/Dockerfile, crystal/lucky/config/error_handler.cr, crystal/lucky/config/log_handler.cr, crystal/lucky/config/route_helper.cr, crystal/lucky/config/server.cr, crystal/lucky/config/session.cr, crystal/lucky/config/static_file_handler.cr, crystal/lucky/shard.yml, crystal/orion/Dockerfile, crystal/raze/Dockerfile, crystal/router.cr/shard.yml, crystal/spider-gazelle/Dockerfile, neph.yaml, php/lumen/Dockerfile, php/lumen/app/Exceptions/Handler.php, php/lumen/app/Http/Controllers/ApplicationController.php, php/lumen/app/Http/Controllers/UserController.php, php/lumen/bootstrap/app.php, php/lumen/composer.json, php/lumen/public/index.php, php/lumen/routes/web.php
Hi,
Latest `crystal`  introduce some **breaking** **changes**
see https://github.com/crystal-lang/crystal/blob/master/CHANGELOG.md
This `PR` tends to update the `crystal` implementations :
+ [x] amber
+ [x] kemal
+ [x] lucky
+ [x] orion
+ [x] raze
+ [x] router.cr
+ [x] spider-gazelle
Regards,
=> Update to crystal 0.27.0

.ci/has_to_run.sh, .ci/lint.sh, .travis.yml
Hi,
As we are testing all frameworks, build times is increasing
This `PR` tends to avoid building unmodified frameworks, fix #505 
Regards,
=> Avoid unecessary builds

.ci/has_to_run.sh, .travis.yml
Hi,
This `PR` avoid running **CI** builds for unmodified **frameworks**, only on `PR`
Branch modification always test all frameworks
Fix #587
=> Optimize ci

python/starlette/requirements.txt
Hi,
This `PR` update [starlette](http://starlette.io)
Regards,
=> Update to starlette 0.7.4

python/quart/requirements.txt, python/responder/requirements.txt, python/starlette/requirements.txt
Hi,
This `PR` update `uvicorn`
Regards,
=> Upgrade uvicorn

.ci/preflight.sh, FRAMEWORKS.yml, node/express/Dockerfile, node/fastify/Dockerfile, node/foxify/Dockerfile, node/hapi/Dockerfile, node/koa/Dockerfile, node/polka/Dockerfile, node/rayo/Dockerfile, node/restify/Dockerfile, node/turbo_polka/Dockerfile
Hi,
This `PR` update our `golang` **framework** to the next major version of `node`
:warning: This is only on the development -> for production it will run on node version available in dists (not docker)
Regards,
=> Update to node 11

README.md, shard.yml
Hi,
This `PR` upgrade [neph](https://github.com/tbrand/neph) build tool to **0.2.10**, allowing to run multiple frameworks in one command
:+1: @tbrand for the work
Running multiple frameworks **COULD** be done with :
~~~
shards install
shards build --release --no-debug
bin/neph flask quart
bin/benchmarker flask quart
~~~
As for the _above_ `example`, [flask](http://palletsprojects.com/p/flask) is compared to [quart](http://pgjones.gitlab.io/quart)
Regards,
=> Multiple jobs

python/quart/requirements.txt
Hi,
This `PR` update `quart` to 0.6.9
Regards,
=> update to 0.6.9

.travis.yml, FRAMEWORKS.yml, go/gf/Dockerfile, go/gf/go.mod, go/gf/main.go, neph.yaml
This PR adds another go framework `GF(GoFrame)` to this amazing project.
=> Add GF(GoFrame) framework

.travis.yml, FRAMEWORKS.yml, go/iris/go.mod
Hi,
This  `PR` update `iris` to the **latest** version, `11.1`.
Regards,
=> Update iris to 11.1

.travis.yml, java/act/pom.xml
Hi,
This `PR` upgrade `act` from `1.8.11` to `1.8.12`
|    | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |Requests / s | Throughput |
|---------------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|--------------:|---------:|
|master | 7.85 ms | 6.97 ms | 11.89 ms | 19.19 ms | 217.31 ms | 6771.00 |  134735.00 | 262.85 MB |
| here | 7.91 ms | 7.06 ms | 12.05 ms | 20.60 ms | 176.03 ms | 5299.00 | 136216.67 | 265.81 MB |
:tada: 
@greenlaw110 What was modified on this version ? 
Regards,
=> Act 1.8.12

.travis.yml, FRAMEWORKS.yml, go/beego/go.mod, java/act/pom.xml, renovate.json
Hi @astaxie @GNURub,
This `PR` update `beego` to **1.11**
Here is a comparison between `1.10` and `1.11` :tada: 
|    | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |Requests / s | Throughput |
|------------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|--------------:|---------:|
| 1.11 | 9.64 ms | 8.47 ms | 15.08 ms | 28.92 ms | 256.65 ms | 7209.33 | 102527.67 | 137.86 MB |
| 1.10 | 9.50 ms | 8.48 ms | 14.74 ms | 28.14 ms | 157.87 ms | 5586.33 | 102744.67 | 137.94 MB |
Regards,
=> Beego 1.11

.travis.yml, FRAMEWORKS.yml, neph.yaml, php/zend-expressive/Dockerfile, php/zend-expressive/composer.json, php/zend-expressive/config/autoload/dependencies.global.php, php/zend-expressive/config/autoload/zend-expressive.global.php, php/zend-expressive/config/config.php, php/zend-expressive/config/container.php, php/zend-expressive/config/pipeline.php, php/zend-expressive/config/routes.php, php/zend-expressive/public/index.php, php/zend-expressive/src/App/src/Handler/Home.php, php/zend-expressive/src/App/src/Handler/User.php, php/zend-expressive/src/App/src/Handler/UserId.php, rust/actix-web/Dockerfile, rust/gotham/Dockerfile, rust/iron/Dockerfile, rust/nickel/Dockerfile, rust/rocket/Dockerfile
~~~
shards install
crystal spec
~~~
=> Add Zend Expressive to PHP

FRAMEWORKS.yml, rust/rocket/Cargo.toml, rust/rocket/src/main.rs
Hi,
This `PR` upgrade `rocket` to version `0.4`
Regards,
=> Update rocket to 0.4

.travis.yml, FRAMEWORKS.yml, neph.yaml, php/zend-framework/Dockerfile, php/zend-framework/composer.json, php/zend-framework/config/application.config.php, php/zend-framework/config/autoload/global.php, php/zend-framework/config/modules.config.php, php/zend-framework/module/Application/config/module.config.php, php/zend-framework/module/Application/src/Controller/IndexController.php, php/zend-framework/module/Application/src/Module.php, php/zend-framework/public/index.php
~~~
shards install
crystal spec
~~~
=> Add Zend Framework to PHP

.travis.yml, FRAMEWORKS.yml, neph.yaml, node/muneem/Dockerfile, node/muneem/app.js, node/muneem/package.json
~~~
shards install
crystal spec
~~~
Addresses #748
=> Add Muneem node framework

rust/rocket/src/main.rs
Hi,
This `PR` disable _logging_ on [Rocket](https://github.com/SergioBenitez/Rocket)
Regards,
=> Disable logging on Rocket

FRAMEWORKS.yml, go/gf/go.mod, go/gf/main.go
=> Upgrade GF to 1.5.2

README.md, python/quart/requirements.txt, python/starlette/requirements.txt
Hi,
This `PR` make
+ **quart**
+ **starlette**
use `uvicorn` `0.4.4`
Regards,
=> Upgrade uvicorn for starlette / quart

.travis.yml, FRAMEWORKS.yml, neph.yaml, python/hug/Dockerfile, python/hug/requirements.txt, python/hug/server.py
Hi,
This `PR` addresses #739 
What was done ?
+ [x] Added on `CI`
+ [x] Added to `FRAMEWORK.yml`
+ [x] Added to `neph.yaml`
+ [x] Test
~~~sh
shards install
shards build --release --no-debug
export FRAMEWORK=hug
crystal spec
~~~
Regards,
=> Introduce hug

.travis.yml, FRAMEWORKS.yml, neph.yaml, python/bocadillo/Dockerfile, python/bocadillo/requirements.txt, python/bocadillo/server.py
Hi,
This `PR` addresses 
+ #951
+ https://github.com/bocadilloproject/bocadillo/issues/150
@florimondmanca Here some results (using `docker` on 4x CPU / 16 Gb)
| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| python (3.7) | [japronto](http://github.com/squeaky-pl/japronto) (0.1) | 4.82 ms | 4.35 ms | 9.11 ms | 15.27 ms | 32.09 ms | 3319.00 | 
| python (3.6) | [vibora](http://vibora.io) (0.0) | 7.32 ms | 6.60 ms | 13.57 ms | 22.76 ms | 66.30 ms | 5016.67 | 
| python (3.7) | [falcon](http://falconframework.org) (1.4) | …
=> Introduce bocadillo

.travis.yml, FRAMEWORKS.yml, neph.yaml, python/fastapi/Dockerfile, python/fastapi/requirements.txt, python/fastapi/server.py
Hi,
This `PR` addresses #950 
@tiangolo How can I produce `text/plain` instead of `application/json` ?
Regards,
=> Introduce fastapi

.travis.yml, FRAMEWORKS.yml, README.md, neph.yaml, python/molten/Dockerfile, python/molten/requirements.txt, python/molten/server.py
Hi,
This `PR` addresses #957 
@Bogdanp could you quick check this `PR` ?
Regards,
=> Introduce molten

FRAMEWORKS.yml, crystal/onyx/shard.yml, crystal/onyx/src/server.cr
Hi,
This `PR` updates https://github.com/onyframework from `0.5.0` to `0.6.3`
Their is a bench on 4 CPU / 8 Gb :tada: 
| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| crystal (0.27) | [onyx](http://github.com/onyxframework/rest) (0.5) | 6.61 ms | 5.86 ms | 10.96 ms | 17.87 ms | 39.60 ms | 3363.67 |
| crystal (0.27) | [onyx](http://github.com/onyxframework/rest) (0.6.3) | 6.49 ms | 5.78 ms | 10.61 ms | 17.52 ms | 34.18 ms | 3220.00 |
Regards,
=> Upgrade onyx

.travis.yml
Hi,
This `PR` try to reduce CI build times using  `travis` **caching** feature
Addresses #851
Followed https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
Regards,
=> cache docker containers

c/kore/Dockerfile
Hi @jorisvink,
We are using `kore` in this benchmarking project.
Could you quick check our implementation in https://github.com/the-benchmarker/web-frameworks/blob/master/c/kore/hello/src/hello.c
Regards,
=> Upgrade to kore 3.2

FRAMEWORKS.yml, swift/vapor/Package.swift
Hi,
This `PR` upgrade `vapor` from `3.0` to `3.2`
@tanner0101 Would you mind if I ping you on each `vapor` **updates** on our side ?
You could help us with `swift` :heart:
=> Upgrade vapor from 3.0 to 3.2

go/beego/Dockerfile, go/chi/Dockerfile, go/chi/go.mod, go/echo/Dockerfile, go/fasthttprouter/Dockerfile, go/gf/Dockerfile, go/gin/Dockerfile, go/iris/go.mod, go/kami/Dockerfile, go/kami/go.mod, go/muxie/Dockerfile
Hi,
This `PR` addresses #998 
Regards,
=> Fix go resolver issue

.travis.yml
Hi,
This `PR` fix the second part of #851 
We avoid travis build (and caching) if not necessay
Regards,
=> Avoid caching unmodified impl

FRAMEWORKS.yml, swift/kitura/Package.swift, swift/perfect/Package.swift, swift/perfect/main.swift, swift/vapor/Package.swift
Hi,
This `PR` upgrade `Perfect` from `3.0` to `3.1`
@iamjono Would you mind if I ping you on each `Perfect` **updates** on our side ?
You could help us with `swift` :heart:
=> upgrade perfect

.travis.yml
Hi,
This  `PR` has a **testing** purpose
I am testing CI
=> force master to be built on CI

FRAMEWORKS.yml, c/agoo-c/Dockerfile, c/agoo-c/simple.c
~~~
shards install
crystal spec
~~~
=> Updated for Agoo-C v0.4.0

python/bocadillo/requirements.txt, python/fastapi/requirements.txt, python/quart/requirements.txt, python/starlette/requirements.txt
Hi,
This `PR` upgrade `uvicorn` to the next major version **0.5.x**
Regards,
PS : @tiangolo @florimondmanca I had to close / re-open this `PR` to avoid unnecessary CI builds (it will be fixed soon)
=> Uvicorn 0.5.0

FRAMEWORKS.yml
Hi,
This `PR` addresses #1047 
`onyx`  has a new home
Regards,
=> Change onyx home

FRAMEWORKS.yml
Hi,
This `PR` addresses #1048 
Update `responder` URL.
Regards,
=> update responder url

README.md
+ [ ] Please check configuration files
+ [ ] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
+ [ ] `FRAMEWORKS.yml`, for **frameworks** list
+ [ ] `travis.yml`, for CI
+ [ ] A `Dockerfile` exists ?
~~~
shards install
crystal spec
~~~
=> Fixed a couple of typos + added pipe

go/chi/go.mod, go/fasthttprouter/go.mod, go/gin/go.mod, go/iris/go.mod, go/kami/go.mod
Hi,
This `PR` addresses :
+ #1020
+ #1019
I've fixed some `go` **modules**
@hmarr Seems to be huge modifications. How @dependabot[bot] will manage that (update only the main dependency ?
@kataras @johngcn Any best-practices you know about **go modules** ?
Regards,
=> fix integrity hashes

FRAMEWORKS.yml
Hi @dlintw,
This `PR` addresses https://github.com/the-benchmarker/web-frameworks/issues/1090
It change `gin` URL
Regards,
=> change URL for gin

FRAMEWORKS.yml, node/restana/app.js, node/restana/package.json
Hi,
This `PR` supersede #1092 
It update `restana` to `2.10.0`
Regards,
=> Update to restana 2.10

FRAMEWORKS.yml, README.md
The version went out of sync with what is being tested by the benchmarking suite. :-)
=> Update Bocadillo version in README

ruby/roda/config.ru
=> Freeze Roda app

.dependabot/config.yml
Hi,
This `PR` add `violetear` to @dependabot config file.
Closes #1174 
Regards,
=> add violetear to dependabot

.travis.yml, FRAMEWORKS.yml, README.md, crystal/athena/Dockerfile, crystal/athena/shard.yml, crystal/athena/src/server.cr, neph.yaml, spec/benchmark_spec.cr
~~~
shards install
crystal spec
~~~
* Adds [Athena](https://github.com/blacksmoke16/athena)
* Updates the `benchmark_spec` file to assert request is successful instead of specifically `200`.
I'm not sure if this would be ok @waghanza?  Reasoning being Athena will return a `204 no content` when using `Nil` return type, which is still successful/valid, but was failing the specs due to the code mismatch.  I can revert it/change the Athena …
=> Add Athena

.dependabot/config.yml
Hi,
This `PR` fix a wrong syntax on `yaml` conf file for @dependabot[bot] 
Closes #1283 
Regards,
=> chore(deps): Wrong identation

FRAMEWORKS.yml, README.md, python/falcon/requirements.txt
Hi,
This `PR` update `falcon` to `2.0.0`
Regards,
/cc @btegs @kgriffs
=> [Python] Update falcon to 2.0.0

FRAMEWORKS.yml, c/agoo-c/Dockerfile, c/kore/Dockerfile
Hi,
This `PR` update :
+  gcc
+ agoo-c
Regards,
=> [C] Use gcc 9.1.0

ruby/agoo/Dockerfile, ruby/cuba/Dockerfile, ruby/flame/Dockerfile, ruby/hanami/Dockerfile, ruby/rack-routing/Dockerfile, ruby/rails/Dockerfile, ruby/roda/Dockerfile, ruby/sinatra/Dockerfile
Hi,
This `PR` update `ruby` to **2.6.3**
Regards,
=> [Ruby] Use ruby 2.6.3

FRAMEWORKS.yml, go/echo/go.mod
Hi,
This `PR` update `echo` to 4.1.5
Regards,
/cc @alexaandru
=> [Go] Update to echo 4.1.5

php/symfony/composer.json
Hi,
This `PR` update `symfony` to `4.2.8`
Regards,
=> [PHP] Use symfony 4.2.8

go/gf/go.mod
Hi,
This `PR` update `gf` to 1.6.11.
Regards,
=> [Go] Update gf to 1.6.11

php/laravel/composer.json
Hi,
This `PR` update `laravel` to the **latest** version
@see https://github.com/laravel/framework/blob/5.8/CHANGELOG-5.8.md
Regards,
=> [PHP] Update laravel to 5.8.17

FRAMEWORKS.yml, README.md, c/agoo-c/Dockerfile, c/kore/Dockerfile, go/echo/go.mod, go/gf/go.mod, kotlin/ktor/gradle.properties, kotlin/ktor/resources/application.conf, nim/jester/Dockerfile, nim/jester/server_nim_jester.nimble, php/laravel/composer.json, php/symfony/composer.json, ruby/agoo/Dockerfile, ruby/cuba/Dockerfile, ruby/flame/Dockerfile, ruby/hanami/Dockerfile, ruby/rack-routing/Dockerfile, ruby/rails/Dockerfile, ruby/roda/Dockerfile, ruby/sinatra/Dockerfile
~~~
shards install
crystal spec
~~~
Update Ktor to version 1.2.0
=> [Kotlin] Update ktor to 1.2.0

.dependabot/config.yml, .travis.yml, FRAMEWORKS.yml, go/gorouter/Dockerfile, go/gorouter/go.mod, go/gorouter/go.sum, go/gorouter/main.go, neph.yaml
~~~
export FRAMEWORK=gorouter
shards install
crystal spec
~~~
=> [Go] Add gorouter

.travis.yml, FRAMEWORKS.yml, neph.yaml, swift/kitura-nio/Dockerfile, swift/kitura-nio/Package.swift, swift/kitura-nio/main.swift, swift/kitura/main.swift
~~~
shards install
crystal spec
~~~
=> [Swift] Add Kitura-NIO

php/lumen/composer.json
Hi,
This `PR` update `lumen` to 5.8.6
Closes #1045 
Regards,
=> [PHP] Update lumen to 5.8.6

README.md
=> [GO] docs: update gin to v1.4

FRAMEWORKS.yml
=> [Go] Update gin to 1.4

README.md, tools/src/benchmarker.cr
I believe the PR checklist doesn't apply for a change this simple :)
=> [Documentation] Ensure all frameworks links are reacheable

java/spring-boot/pom.xml, java/spring-boot/src/main/resources/application.properties
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Java] Use Spring boot with webflux

.dependabot/config.yml, .travis.yml, java/act/Dockerfile, java/rapidoid/.gitignore, java/rapidoid/Dockerfile, java/rapidoid/config.yaml, java/rapidoid/pom.xml, java/rapidoid/src/main/java/benchmark/rapidoid/Main.java, java/rapidoid/src/main/resources/config.yml, java/spring-boot/.gitignore, java/spring-boot/Dockerfile, java/spring-boot/pom.xml
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Java] Add rapidoid

.dependabot/config.yml, .travis.yml, README.md, python/blacksheep/Dockerfile, python/blacksheep/config.yaml, python/blacksheep/requirements.txt, python/blacksheep/server.py
Hi,
This `PR` add [BlackSheep](https://github.com/RobertoPrevato/BlackSheep)
/cc @RobertoPrevato could you check this code ?
Closes #1505 
-----------------------------------------------------
~~~sh
~~~
~~~sh
~~~
~~~
ex) FRAMEWORK=<MY_FRAMEWORK>
shards install
crystal spec
~~~
-------------------------------------------
Regards,
=> [Python] Introduce blacksheep

.travis.yml, README.md, swift/kitura-nio/Package.swift, swift/kitura/Package.swift, swift/perfect/Dockerfile, swift/perfect/Package.swift, swift/swifter/Dockerfile, swift/swifter/Package.swift, swift/swifter/config.yaml, swift/swifter/main.swift, swift/vapor/Package.swift
Hi,
This `PR` add `swifter`
Closes https://github.com/the-benchmarker/web-frameworks/issues/1378
@julien-c @Vkt0r When building with `swift build -c release`, no **binary** are created in `.build` directory.
How can I build / lauch `swifter` ?
PS : I have no `swift` skills
=> [Swift] Introduce swifter

.dependabot/config.yml, node/nanoexpress/Dockerfile, node/nanoexpress/app.js, node/nanoexpress/config.yaml, node/nanoexpress/package.json
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
This PR closes #1588
=> [Javascript] Add nanoexpress

node/nanoexpress/app.js, node/nanoexpress/package.json
=> [Javascript] Use turbo-way of response on nanoexpress

node/nanoexpress/app.js, node/nanoexpress/package.json
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Javascript] Update nanoexpress to latest and improve performance

.travis.yml, go/gramework/Dockerfile, go/gramework/config.yaml, go/gramework/go.mod, go/gramework/main.go
Hi,
This `PR` adds [gramework](https://github.com/gramework/gramework)
Closes #1135 
/cc @kirillDanshin
=> [Go] Introduce gramework

.dependabot/config.yml, .travis.yml, go/air/Dockerfile, go/air/config.yaml, go/air/go.mod, go/air/main.go
This closes #1683.
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Go] Add Air

.travis.yml, go/atreugo/Dockerfile, go/atreugo/config.yaml, go/atreugo/go.mod, go/atreugo/main.go, go/beego/Dockerfile, go/chi/Dockerfile, go/echo/Dockerfile, go/fasthttprouter/Dockerfile, go/gf/Dockerfile, go/gin/Dockerfile, go/gorilla-mux/Dockerfile, go/gorouter/Dockerfile, go/gramework/Dockerfile, go/kami/Dockerfile, go/violetear/Dockerfile
Hi,
This `PR` add [atreugo](https://github.com/savsgio/atreugo)
Closes #1653 
/cc @savsgio
=> [Go] Introduce atreugo

.dependabot/config.yml, .travis.yml, go/air/Dockerfile, go/atreugo/Dockerfile, go/beego/Dockerfile, go/chi/Dockerfile, go/echo/Dockerfile, go/fasthttprouter/Dockerfile, go/gf/Dockerfile, go/gin/Dockerfile, go/gorilla-mux/Dockerfile, go/goroute/Dockerfile, go/goroute/config.yaml, go/goroute/go.mod, go/goroute/go.sum, go/goroute/main.go, go/gorouter/Dockerfile, go/gramework/Dockerfile, go/kami/Dockerfile, go/rte/Dockerfile, go/violetear/Dockerfile
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
Closes #1684
=> Add goroute framework

.travis.yml, tools/src/make.cr
Hi,
This `PR` closes #1702. 
It appears that linting from `CI` causes `CI`  failing, and then the **test** stage does not occurs.
Linting will return, but in an other way, a **pre-commit** hooks, or else.
Regards,
=> feat(ci): Remove lint from CI

python/tornado/server.py
=> Updating tornado handler to return 200 only with empty response

.dependabot/config.yml, .travis.yml, README.md, ruby/syro/Dockerfile, ruby/syro/Gemfile, ruby/syro/app.rb, ruby/syro/config.ru, ruby/syro/config.yaml
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Ruby] Adds syro to the benchmarks

go/gramework/go.mod
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Go] Fix gramework build on go 1.13

.dependabot/config.yml, .travis.yml, php/imi/.gitignore, php/imi/ApiServer/Controller/IndexController.php, php/imi/ApiServer/Main.php, php/imi/ApiServer/config/config.php, php/imi/Dockerfile, php/imi/Main.php, php/imi/composer.json, php/imi/config.yaml, php/imi/config/beans.php, php/imi/config/config.php
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [PHP] Added imi framework.

.dependabot/config.yml, .travis.yml, README.md, perl/dancer2/Dockerfile, perl/dancer2/config.yaml, perl/dancer2/cpanfile, perl/dancer2/d2app.psgi
Hi,
Thanks @veryrusty fr your code.
This `PR` add [dancer2](https://github.com/PerlDancer/Dancer2)
Closes #1756 
/cc @xsawyerx
=> [Perl] Add dancer

.dependabot/config.yml, .travis.yml, clojure/config.yaml, nim/config.yaml, tools/src/make.cr
Hi,
This `PR` fix a version issue.
For exampel, `0.20` was shown as `0.2` due to a float cast.
Regards,
=> Fix version mess

.travis.yml, README.md, crystal/toro/Dockerfile, crystal/toro/config.yaml, crystal/toro/shard.yml, crystal/toro/src/toro.cr, perl/config.yaml
Hi,
This `PR` add https://github.com/soveran/toro
Closes #1259 
Regards,
/cc @soveran
=> [Crystal] Introduce toro

tools/src/benchmarker.cr
Hi,
This `PR` closes #1772 
Regards,
=> Remove trailing whitespace in results

README.md, java/javalin/Dockerfile, java/javalin/config.yaml, java/javalin/pom.xml, java/javalin/src/main/java/benchmark/javalin/Bench.java
Hi,
This `PR` add https://github.com/tipsy/javalin
Closes #1162 
@tipsy Could you check my code ? I'm very new (again) to java world
With the plethora of builds tools (**gradle**, **maven**, ...), I'm lost
What is the common use case in `java` world ?
Is it really to use `java` **8** ?
/cc @greenlaw110 @david-m-s
=> [Java] Introduce javalin

.dependabot/config.yml, .travis.yml, python/asgineer/Dockerfile, python/asgineer/config.yaml, python/asgineer/requirements.txt, python/asgineer/server.py
Hi,
This `PR` add `asgineer` in `here`
@almarklein Could you review ths one ?
The purpose is to be as-close-as a **production-ready** code
Regards,
-------------
Closes #1337
=> [Python] Add asgineer

.dependabot/config.yml, .travis.yml, nim/httpbeast/Dockerfile, nim/httpbeast/config.yaml, nim/httpbeast/server.nim, nim/httpbeast/server.nimble
Hi @dom96,
This `PR` adds https://github.com/dom96/httpbeast.
Could you review / approve this `PR` ?
Regards,
-----------
Closes #295
=> [Nim] Introduce httpbeast

.dependabot/config.yml, .travis.yml, README.md, ruby/grape/Dockerfile, ruby/grape/Gemfile, ruby/grape/config.ru, ruby/grape/config.yaml
Hi,
This `PR` adds http://www.ruby-grape.org/ here.
@dblock Could you review this `PR` ?
The purpose is to have a as-close-as **real-world** implementation.
Regards,
---------
Close #1168
=> [Ruby] Introduce grape

fsharp/suave/config.yaml
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [suave] remove https prefix from website property in config.yaml

php/hyperf/Dockerfile, php/imi/Dockerfile, php/imi/config/config.php, php/one/Dockerfile, php/swoft/Dockerfile
* Use CoServer Mode by imi v1.0.13
* Update swoole version to 4.4.7
=> [PHP] Update imi

README.md, tools/src/benchmarker.cr
Hi,
This `PR` closes #1815. 
It sort results by latency average instead of latency 50th percentile.
Regards,
=> Sort by average

.dependabot/config.yml, .travis.yml, README.md, python/clastic/Dockerfile, python/clastic/config.yaml, python/clastic/requirements.txt, python/clastic/server.py
Hi,
This `PR` closes #1823
Its add https://github.com/mahmoud/clastic in `here`
/cc @mahmoud
Could yo please review this `PR`
=> [Python] Add clastic

cpp/drogon/Dockerfile, swift/kitura-nio/Package.swift, swift/kitura-nio/config.yaml, swift/kitura/Package.swift, swift/kitura/config.yaml
Hi @djones6,
This `PR` update [kitura](https://www.kitura.io)
Regard,
=> [Swift] Update kitura

cpp/drogon/Dockerfile
Hi @an-tao,
This `PR` update [drogon](https://github.com/an-tao/drogon)
Regard,
=> [C++] Update drogon to 1.0b8

java/javalin/config.yaml, java/javalin/pom.xml
Hi @tipsy,
This `PR` update [javalin](https://javalin.io)
Regard,
=> [Java] Update javalin to 3.5

c/kore/Dockerfile, c/kore/config.yaml
Hi @jorisvink,
This is a `PR` that update [kore](https://github.com/jorisvink/kore)
Regard,
=> [C] Update kore

.dependabot/config.yml, .travis.yml, ruby/camping/Dockerfile, ruby/camping/Gemfile, ruby/camping/app.rb, ruby/camping/config.ru, ruby/camping/config.yaml
Hi,
This `PR` closes #661  -> adding [camping](https://github.com/camping/camping) `here`
/cc @judofyr Could you check this code ?
Regards,
=> [Ruby] Add camping

c/agoo-c/Dockerfile, c/agoo-c/config.yaml, c/agoo-c/simple.c
Hi @ohler55,
This is a `PR` that update [agoo-c](https://github.com/ohler55/agoo-c)
@OvermindDL1 Any suggestion 
Regard,
=> [C] Update agoo-c to 0.7

go/gorouter/config.yaml, go/gorouter/go.mod
=> Bump gorouter version

node/hapi/app.js, node/hapi/config.yaml, node/hapi/package.json
Hi,
This `PR` closes #1879 
`hapi` has been renamed in `@hapi/hapi`
@see https://www.npmjs.com/package/hapi
Regards,
=> [Javascript] Rename hapi package

php/imi/ApiServer/Controller/IndexController.php
=> [PHP] Fix imi

cpp/drogon/config.yaml
=> [C++] Update drogon to 1.0b10

java/micronaut/src/main/java/micronaut/controller/BenchController.java
Fixing the Micronaut controller implementation because blocking types are used but the methods are not blocking. Also the package was incorrect
=> Move operations to the event loop

cpp/drogon/config.yaml
=> [C++] Update drogon to 1.0b11

.dependabot/config.yml, javascript/nanoexpress-pro/app.js, javascript/nanoexpress-pro/config.yaml, javascript/nanoexpress-pro/package.json
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Javascript] Add nanoexpress Pro

go/atreugo/config.yaml, go/atreugo/go.mod
~~~sh
~~~
~~~sh
~~~
~~~
shards install
crystal spec
~~~
=> [Go] Upgrade atreugo to v9.0.1

.dependabot/config.yml, .travis.yml, java/spring-framework/config.yaml, java/spring-framework/pom.xml, java/spring-framework/src/main/java/benchmark/springframework/BenchmarkController.java, java/spring-framework/src/main/java/benchmark/springframework/WebAppInitializer.java, java/spring-framework/src/main/java/benchmark/springframework/WebConfiguration.java
Add implementation with bare spring framework (no spring boot). Use jetty runner as servlet container.
#446
=> Add java spring-framework

crystal/Dockerfile, crystal/onyx/config.yaml, tools/src/make.cr
Hi,
This `PR` closes #2018 
It :
+ [x] Upgrade [spider-gazelle](https://spider-gazelle.net)
+ [x] Add compilation option to `onyx`
Thanks to @Daniel-Worrall for his solution for `onyx`
Regards,
=> feat(onyx): Add build flags

go/router/config.yaml, go/router/go.mod, go/router/main.go
Hi @savsgio,
This `PR` adds https://github.com/fasthttp/router
I'm a little dubitative about results : 
| Language | Framework | Average | 50th percentile | 90th percentile | Standard deviation | Requests / s | Throughput |
|----|----|--------:|------------:|--------:|---------:|-------:|----|
| go (1.13)| atreugo (9.0) | **4.05** ms | 3.11 ms | 7.18 ms | 3880.33 | 238660.33 | 31.82 Mb |
| go (1.13)| fasthttprouter (0.1) | **4.27** ms | 3.28 ms | 7.73 ms | 3742.33 | 226205.00 | 24.35 Mb |
| go (1.13)| router (1.6) | **4.52** ms | 2.85 ms | 6.67 ms | 13067.00 | 258054.00 | 27.49 Mb |
| go (1.13)| gorouter-fasthttp (4.2) | **5.07** ms | 3.13 ms | 7.22 ms | 15060.00 | 240088.00 | 25.48 Mb |
| go (1.13)| rte (0.0) | **6.40** ms | 4.34 ms | 10.73 ms | 15677.00 | 189242.67 | 16.79 Mb |
| go …
=> [Go] Introduce router

php/Dockerfile, php/config.yaml
Hi,
This `MR` upgrade `PHP` to **7.4**
Regards,
----------------------------
Closes : #2036
=> [PHP] Upgrade to 7.4

rust/Dockerfile, rust/config.yaml
Hi,
This `PR` update `rust` to **1.39**
Regars,
-----------------
Closes #2049
=> [Rust] Update to 1.39

.ci/template.mustache, .dependabot/config.yml, .travis.yml, javascript/nanoexpress-pro/package.json, javascript/sifrr/package.json, php/hamlet/composer.json, php/hamlet/config.yaml, php/hamlet/public/index.php, php/hamlet/src/Application.php, php/hamlet/src/Application/Resources/ApplicationResource.php, php/hamlet/src/Application/Resources/UserIDResource.php, php/hamlet/src/Application/Resources/UserResource.php
Hi @vasily-kartashov,
This `PR` adds `hamlet` here.
Could you check my codebase, I'm not sure about it, specially routing part ;-)
Regards,
PS : I'll flag this **frameworks** as experimental since I had to use `dev` as a `minimum-requirements`
------------------------------
Closes #1920
=> [PHP] Introduce hamlet

go/fasthttp/go.mod, go/fasthttprouter/go.mod, go/gorouter-fasthttp/go.mod
Hi,
This is an **aggregate** `PR`.
It updates `fasthttp` to `1.7.1`.
Regards,
=> [Go] Update fasthttp to 1.7.1

perl/Dockerfile
Hi,
This `PR` reduce build time for `perl` **containers**
It simply avoid running test (using `-n`).
Regards,
---------------------------------
Closes #2089
=> [Perl] Reduce build time

.dependabot/config.yml, tools/src/make.cr
Hi,
This `PR` re-enable tracking updates for **docker** for some languages
+ [x] nim
+ [x] rust
+ [x] julia
+ [x] csharp
+ [x] kotlin
+ [x] perl
+ [x] fsharp
+ [x] swift
------------------------------
Closes #2109
=> Track docker update, partially

go/atreugo/config.yaml, go/atreugo/go.mod
Hi,
This `PR` update https://github.com/savsgio/atreugo to `10.0`.
Regards,
------------------------
Closes #2131
=> [Go] Update atreugo to 10.0

python/masonite/bootstrap/start.py, python/masonite/wsgi.py
-------------------------
Edit closes #2151
=> Update Masonite for v2.3

go/fasthttp/config.yaml, go/fasthttp/go.mod, go/fasthttprouter/go.mod, go/gorouter-fasthttp/go.mod
Hi,
This `PR` upgrade `fasthttp` to **1.8.0**
Regards,
=> [Go] Update fasthttp to 1.8.0

.travis.yml, nim/phoon/config.yaml, nim/phoon/server.nim, nim/phoon/server.nimble
Hi :)
For several month now, I have been working on a new Nim web framework called [Phoon](https://github.com/ducdetronquito/phoon).
It aims to be an alternative to [Httpbeast](https://github.com/dom96/httpbeast), [Jester](https://github.com/dom96/jester) or [Rosencrantz](https://github.com/andreaferretti/rosencrantz) by providing an API inspired by [ExpressJS](https://github.com/expressjs/express).
Phoon is first developed with user experience in mind and no performance optimizations has been made yet. But thanks to your wonderful initiative, I plan to keep track of the overall performance of Phoon and eventually improve its internals !
Again, thanks for your work and let me now if some modifications are needed for this PR !
Have a nice day 🤸
=> [Nim] Add Phoon 🐇⚡

go/gorouter-fasthttp/go.mod, go/gorouter-fasthttp/main.go, go/gorouter/go.mod
Hi @vardius,
This `PR` updates `gorouter` to **4.2.2**
Thanks for your updates, but no need to have one `PR` per commit :stuck_out_tongue: (I've combien them `here`).
I'm computing the results, now
@dutradda @douglasfarinelli Results will include `apidaora`
Regards,
--------------
Closes #2219  #2220 #2221
=> [Go] Update to gorouter 4.2.2

csharp/Dockerfile, csharp/aspnetcore/config.yaml, csharp/config.yaml, fsharp/Dockerfile, fsharp/config.yaml
Hi,
This `PR` use the latest (**3.1**) version on dot net core
@see https://dotnet.microsoft.com/download/dotnet-core/3.1
@sebastienros @Eilon @rynowak Could you quick-look this `PR` ?
--------------
Closes https://github.com/the-benchmarker/web-frameworks/issues/2157
=> [C# + F#] Update dot net core v3.1

README.md, php/workerman/config.yaml
New GitHub link: https://github.com/walkor/Workerman
=> Fixed broken url to php Workerman in README

.dependabot/config.yml, .travis.yml, go/httprouter/config.yaml, go/httprouter/go.mod, go/httprouter/go.sum, go/httprouter/main.go
See https://github.com/julienschmidt/httprouter
Closed https://github.com/the-benchmarker/web-frameworks/issues/434
=> chore(go): add httprouter

go/fiber/config.yaml, go/fiber/go.mod, go/fiber/main.go
Hi,
This `PR` update fiber to 1.7.1
Thanks @Fenny 
Regards,
-------------
Closes #2291
=> [Go] Update fiber to 1.7.1

crystal/Dockerfile
That should make a difference in benchmarks ;)
=> Build Crystal shards in release mode

go/Dockerfile, go/config.yaml
See https://blog.golang.org/go1.14
Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>
=> chore(go): update to go 1.14

crystal/lucky/src/actions/errors/show.cr, crystal/lucky/src/actions/home/index.cr, crystal/lucky/src/server.cr
I haven't tested this locally so hoping CI passes 🤞
=> Add multi-core to Lucky and fix deprecations

crystal/grip/config.yaml, crystal/grip/shard.yml, crystal/grip/src/server.cr
- Fixed the naming.
- Removed logging from the framework.
=> Update the framework from 0.27.0 to 0.28.0

php/workerman/composer.json, php/workerman/config.yaml, php/workerman/start.php
=> Upgrade workerman to 4.x

crystal/lucky/config.yaml, crystal/lucky/shard.yml
Hi,
This `PR` upgrades `lucky` to **0.19**
/cc @paulcsmith @jwoertink @j8r @Sija feel free to check and optimize this
Regards,
-------------
Closes #2389
=> [Crystal] Update lucky to 0.19

crystal/orion/config.yaml, crystal/orion/shard.yml, nim/httpbeast/config.yaml
Hi,
This `PR` update `orion` to **2.3**
/cc @jwaldrip
Regards,
------------
Closes #2390
=> [Crystal] Update orion to 2.3

nim/httpbeast/config.yaml
Hi,
`httpbeast` is displayed as version **0.2**, or the setup has the version **2.2**
Regards,
------------
Closes #2388
=> [Nim] Wrong version displayed for httpbeast

.travis.yml, crystal/ricr/config.yaml, crystal/ricr/shard.yml, crystal/ricr/src/server.cr
A new Crystal web-framework, with automatic Swagger/OpenAPI support.
=> [Crystal] Introduce ricr

php/simps/app/Controller/IndexController.php, php/simps/config.yaml, php/simps/config/servers.php
@waghanza Please review this.
You can close #2439 , thanks.
=> [PHP] Update for simps

php/basicphp/functions.php
Should check for $_SERVER['REMOTE_ADDR'] to be set before accessing it.
=> Check for REMOTE_ADDR

crystal/lucky/config.yaml, crystal/lucky/shard.yml
Hi,
This `PR` updates `lucky` to `0.20`.
Regards,
=> [Crystal] Update lucky to 0.20

crystal/Dockerfile, crystal/config.yaml
Hi,
This `PR` upgrades `crystal` to **v0.34**
Regards,
=> [Crystal] Upgrade to 0.34

.ci/has_to_run.sh, javascript/Dockerfile, javascript/config.yaml
=> [Javascript] Upgrade node to 13.12

julia/Dockerfile, julia/config.yaml
=> [Julia] Upgrade containers to v1.4

rust/Dockerfile, rust/config.yaml
=> [Rust] Upgrade containers to 1.42

swift/kitura-nio/Package.swift, swift/kitura-nio/config.yaml, swift/kitura/Package.swift, swift/kitura/config.yaml
Hi,
This `PR` update https://github.com/IBM-Swift/Kitura to **2.9**
Regards,
/cc @djones6
=> [Swift] Update kitura to 2.9

java/micronaut/build.gradle, java/micronaut/gradle.properties
Hi,
This `PR` update `micronaut` to **1.3**
Regards,
=> [Java] Upgrade micronaut to 1.3

java/spring-boot/config.yaml, java/spring-boot/pom.xml
Hi,
This `PR` update _spring-boot_ to **2.2**
Regards,
/cc @wilkinsona @snicoll
=> [Java] Update spring-boot to 2.2

swift/Dockerfile, swift/config.yaml
=> [Swift] Upgrade to 5.2

java/micronaut/config.yaml, kotlin/Dockerfile
=> Upgrade to gradle 6.3

.dependabot/config.yml, .travis.yml, go/tango/config.yaml, go/tango/go.mod, go/tango/main.go
Hi @lunny,
This `PR` add `tango`. 
Could you please check this code, and give me your advices :heart: 
Purpose is to have **production-grade** implementations `here` so we can compare (performances) on factual basis.
Regards,
------------------------------------
Closes #2506
=> [Go] Add tango

php/phalcon/config.yaml
Hi,
This `PR` is **pecl** _package_ for `phalcon`.
/cc @ruudboon @niden
Regards,
------------------
Closes #2512
=> [PHP] Use phalcon pecl package

.dependabot/config.yml, .travis.yml, format.yaml, java/jooby/.gitignore, java/jooby/config.yaml, java/jooby/pom.xml, java/jooby/src/main/java/benchmark/App.java, kotlin/kooby/.gitignore, kotlin/kooby/build.gradle, kotlin/kooby/config.yaml, kotlin/kooby/settings.gradle, kotlin/kooby/src/main/kotlin/benchmark/App.kt
HI @jknack,
This is a redo of #2509. I still can not push (_permission denied_) on your repo.
As a workaround, I've edited you code base, and create this `PR` with your commits
---------------
Closes #2509
=> [Java] Add jooby

.travis.yml, pony/Dockerfile, pony/config.yaml, pony/jennet/bundle.json, pony/jennet/config.yaml, pony/jennet/main.pony
Add pony: https://www.ponylang.io/ 
with [Jennet](https://github.com/Theodus/jennet) web framework
=> add pony lang

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to 3.0

crystal/ricr/config.yaml, crystal/ricr/shard.yml
=> [Crystal] Update ricr to 0.2

go/fiber/config.yaml
Hi,
This `PR` update https://github.com/gofiber/fiber website
/cc @Fenny 
Regards,
=> [Go] Update fiber website

go/gin/go.mod
https://github.com/gin-gonic/gin/releases/tag/v1.6.3
=> chore(go): upgrade gin to 1.6.3 for performance issue

php/fastsitephp/composer.json, php/fastsitephp/config.yaml, php/fastsitephp/public/index.php
Hi @ConradSollitt,
Following #2680, this is an attemt to add `fastsitephp` in here.
The purpose is to have **production-grade** implementation, then please feel free to review thinking this should be deployable as-is (safe, readable ...).
Regards,
PS : All `php` **frameworks** here a tracked by `renovatebot` to ensure to have an up-to-date version. May I ask for you review on each update ?
------------
Closes #2680
=> [PHP] Add fastsitephp

.travis.yml, nim/rosencrantz/config.yaml, nim/rosencrantz/server.nim, nim/rosencrantz/server.nimble
After I played a little with rosencrantz framework I thought it would be nice to add it. 
I hope don't mind @andreaferretti.
I checked all the routes with Postman and worked fine. 
--------
Closes #335
=> Add rosencrantz framework

fsharp/websharper/Main.fs
Correct production usage of empty body and text encoding. See https://github.com/dotnet-websharper/core/issues/1105
=> [F#] WebSharper Updates

fsharp/frank/Program.fs, fsharp/frank/config.yaml, fsharp/frank/web.fsproj
=> [F#] Frank Update to 6.1

.travis.yml, php/chubbyphp-roadrunner/.rr.yaml, php/chubbyphp-roadrunner/composer.json, php/chubbyphp-roadrunner/config.yaml, php/chubbyphp-roadrunner/public/index.php
chubbyphp-roadrunner is same as chubbyphp but using roadrunner instead of php-fpm.
=> chubbyphp-roadrunner

.travis.yml, go/gearbox/config.yaml, go/gearbox/go.mod, go/gearbox/main.go
Gearbox is a web framework written in Go with a focus on high performance and memory optimization.
=> [Go] Add Gearbox

go/gearbox/main.go
made a small update which could lead to a faster performance.
=> updated gearbox benchamrk code

csharp/aspnetcore/Startup.cs
See https://github.com/the-benchmarker/web-frameworks/pull/2922#discussion_r440275940
cc @davidfowl
=> Remove AddRouting, which is unnecessary

.travis.yml, csharp/simplify.web/Controllers/HomeController.cs, csharp/simplify.web/Controllers/UserController.cs, csharp/simplify.web/Controllers/UserIdController.cs, csharp/simplify.web/Program.cs, csharp/simplify.web/Startup.cs, csharp/simplify.web/config.yaml, csharp/simplify.web/web.csproj
Closes #2973 
NOTE: I'm not familiar with this library, so I'm not sure that my route processing to retrieve the userId is standard or not.
=> [C#] Add Simplify.Web #2973

go/gearbox/go.mod, go/gearbox/main.go
=> [Go] Optimize gearbox

.github/CODEOWNERS, .travis.yml, crystal/runcobo/config.yaml, crystal/runcobo/shard.yml, crystal/runcobo/src/server.cr
Hi @shootingfly,
The route `"/user/:id"` seems not to work. I have `Missing param name: "id" (KeyError)`.
Regards,
------------
Closes #2958
=> [Crystal] Add runcobo

.travis.yml, nim/Dockerfile, nim/akane/config.yaml, nim/akane/server.nim, nim/akane/server.nimble
Hi @Ethosa,
Following https://github.com/Ethosa/akane/issues/1, this `PR` adds `akane` in here.
Thanks for your help :tada:
However, is there any way to :
+ send `plain/text` instead of **json** or **html**
+ avoid having `<head><meta charset='utf-8'></head>` while `response.answer`
Also, I have `SIGSEGV: Illegal storage access. (Attempt to read from nil?)` for routes `/user/:id` and `/user`
Regards,
=> [Nim] Add akane

.travis.yml, php/mark/composer.json, php/mark/config.yaml, php/mark/start.php
Add Mark.
Mark is a high performance micro framework based on workerman helps you quickly write simple APIs with php.
Thank you for your project 👍
=> [PHP] Add Mark

.travis.yml, java/struts2/.gitignore, java/struts2/config.yaml, java/struts2/pom.xml, java/struts2/src/main/java/org/apache/struts/benchmarker/example/UserAction.java, java/struts2/src/main/resources/log4j2.xml, java/struts2/src/main/resources/struts.xml, java/struts2/src/main/webapp/WEB-INF/index.jsp, java/struts2/src/main/webapp/WEB-INF/user-id.jsp, java/struts2/src/main/webapp/WEB-INF/web.xml
=> [Java] Add struts

.github/CODEOWNERS, java/struts2/src/main/webapp/WEB-INF/index.jsp, java/struts2/src/main/webapp/WEB-INF/user-id.jsp
Refs https://github.com/the-benchmarker/web-frameworks/pull/3005#pullrequestreview-435706476
=> Uses proper content type

.travis.yml, php/comet/composer.json, php/comet/config.yaml, php/comet/start.php
Would like to see Comet between other PHP frameworks :)
Original framework: https://github.com/gotzmann/comet
---------
Closes #2942
=> Add Comet v0.7 into PHP frameworks

.github/CODEOWNERS, php/chubbyphp-roadrunner/composer.json, php/chubbyphp-roadrunner/config.yaml, php/chubbyphp-roadrunner/public/index.php, php/chubbyphp/composer.json, php/chubbyphp/config.yaml, php/chubbyphp/public/index.php, tools/src/make.cr
=> [PHP] Update chubbyphp to 3.0

java/act/pom.xml
Hi,
This `PR` fixes `act`. `act-asm` was not available for the latest version.
Regards,
-----------
Closes #3045
=> [Java] Update act to 1.8.33

.travis.yml, php/sunrise-router-annotations/composer.json, php/sunrise-router-annotations/config.yaml, php/sunrise-router-annotations/public/index.php, php/sunrise-router-annotations/src/Controller/HomeController.php, php/sunrise-router-annotations/src/Controller/User/UserCreateController.php, php/sunrise-router-annotations/src/Controller/User/UserListController.php, php/sunrise-router-annotations/src/Controller/User/UserReadController.php, php/sunrise-router/composer.json, php/sunrise-router/config.yaml, php/sunrise-router/public/index.php
=> [PHP] Sunrise Router

java/Dockerfile, java/blade/pom.xml, java/config.yaml, java/javalin/pom.xml, java/jooby/pom.xml, java/light-4j/config.yaml, java/light-4j/pom.xml, java/rapidoid/pom.xml, java/spring-boot/pom.xml, java/spring-framework/config.yaml, java/spring-framework/pom.xml, java/struts2/config.yaml, java/struts2/pom.xml
Hi,
This `PR` update `java` to **11**
Frameworks :
+ [x] act
+ [x] blade
+ [x] javalin
+ [x] jooby
+ [x] light-4j
+ [x] micronaut
+ [x] rapidoid
+ [x] spring-boot
+ [x] spring-framework
+ [x] struts2
Regards,
/cc @lukaszlenart @jknack @greenlaw110 
--------
Closes #3098
=> [Java] Upgrade to v11

java/struts2/config.yaml, java/struts2/pom.xml, java/struts2/src/etc/assembly.xml, java/struts2/src/main/java/App.java, java/struts2/src/main/java/org/apache/struts/benchmarker/example/PlainResult.java, java/struts2/src/main/java/org/apache/struts/benchmarker/example/UserAction.java, java/struts2/src/main/resources/struts.xml, java/struts2/src/main/webapp/WEB-INF/index.jsp, java/struts2/src/main/webapp/WEB-INF/user-id.jsp, java/struts2/src/main/webapp/WEB-INF/web.xml
This PR uses an embedded Jetty instead of deprecated jetty-runner and also uses new PlainResult instead of JSPs
=> Embedded jetty

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] update spider-gazelle to v3.3.0

java/struts2/pom.xml
Fixes problem with missing jetty-jsp version in #3134
=> Splits versions for jetty and jetty-jsp

php/codeigniter4/composer.json, php/codeigniter4/config.yaml
=> [PHP] CodeIgniter config updates

javascript/Dockerfile, javascript/config.yaml
Hi,
This `PR` upgrade `node` to v14.7
Regards,
=> [Javascript] Upgrade node to v14.7

tools/src/db.cr
Hi,
This `PR` allow to use `gilab` shrtcut in `config.yaml`
Regards,
------------
Closes #3226
=> feat(config): Add gitlab shortcut

.travis.yml, python/index.py/config.yaml, python/index.py/requirements.txt, python/index.py/server.py
https://github.com/abersheeran/index.py
=> [Python] Add index.py

crystal/runcobo/config.yaml, crystal/runcobo/src/server.cr
Hi @shootingfly,
This `PR` updates https://github.com/runcobo/runcobo to **1.0**
Regards,
------
Closes #3273
=> [Crystal] Update runcobo to 1.0

crystal/shivneri/config.yaml, crystal/shivneri/shard.yml
Hi @ujjwalguptaofficial,
We updates `shivneri` to **0.16** 🎉 
Regards,
---------
Closes #3019
=> [Crystal] Update shivneri to 0.16

crystal/grip/config.yaml, crystal/grip/shard.yml, crystal/grip/src/server.cr
Hi @grkek,
This `PR` updates https://github.com/grip-framework/grip to **1.0**
Regards,
=> [Crystal] Update grip to v1.0

java/act/src/main/resources/logback.xml, java/javalin/pom.xml, java/jooby/pom.xml, java/rapidoid/pom.xml, java/spring-boot/src/main/resources/application.properties, java/spring-framework/src/main/resources/application.properties, java/struts2/src/main/resources/log4j2.xml, kotlin/kooby/build.gradle
Hi,
This `PR` disable logging on all `java` frameworks.
Logging is disabled for :
+ [x] act
+ [x] blade
+ [x] javalin
+ [x] jooby
+ [x] micronaut
+ [x] rapidoid
+ [x] spring-boot
+ [x] spring-framework
+ [x] struts2
Regards,
=> [Java] Disable logging

.github/CODEOWNERS, rust/actix/Cargo.toml, rust/actix/config.yaml, rust/actix/src/main.rs
superceeds #3307 
---
Closes #3307
=> [Rust] Update actix-web to v3.0.0

.github/CODEOWNERS, .travis.yml, go/goyave/config.json, go/goyave/config.yaml, go/goyave/go.mod, go/goyave/main.go
Added [Goyave](https://github.com/System-Glitch/goyave/).
Closes #2647
=> [Go] Add Goyave

perl/dancer2/config.yaml, perl/dancer2/cpanfile
Hi,
This `PR` specify `dancer2` **version**
Regards,
-----------
Closes #3253
=> [Perl] Specify version for dancer2

nim/jester/config.yaml, nim/jester/server.nimble
=> [Nim] Update jester to v0.5

crystal/athena/config.yaml, crystal/athena/shard.yml
=> [Crystal] Update athena to 0.11

cpp/drogon/config.yaml
=> [C++] Update drogon to v1.1

.github/CODEOWNERS, php/phalcon/composer.json, php/phalcon/config.yaml
Hi,
This `PR` updates phalcon to 4.1
Regards,
------------
@niden @ruudboon May I notify you on each `phalcon` update here ?
=> [PHP] Update phalcon to 4.1

.semaphore/semaphore.yml, java/restheart/.gitignore, java/restheart/config.yaml, java/restheart/pom.xml, java/restheart/restheart.yml, java/restheart/src/main/java/benchmark/restheart/RootService.java, java/restheart/src/main/java/benchmark/restheart/UserService.java
this PR adds [RESTHeart](https://restheart.org) to the java frameworks
Please note that I could not run and test it via `neph` due to incomplete documentation in README.This PR definitely needs a check!
**PLEASE** update the readme (for instance it refers to `make config` but not `config` target is defined).
=> [java] Add RESTHeart

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
Hi @stakach,
This `PR` updates https://spider-gazelle.net/ to **3.4**
Regards,
-------
Closes #3469
=> [Crystal] Update spider-gazelle to 3.4

crystal/kemal/config.yaml, crystal/kemal/shard.yml
Hi,
This `PR` upgrades https://github.com/kemalcr/kemal to **0.27**
Regards
-------------
Closes #3018
=> [Crystal] Update kemal to 0.27

java/spring-framework/.gitignore, java/spring-framework/config.yaml, java/spring-framework/pom.xml, java/spring-framework/src/etc/assembly.xml, java/spring-framework/src/main/java/App.java, java/spring-framework/src/main/java/benchmark/springframework/WebAppInitializer.java, java/spring-framework/src/main/java/benchmark/springframework/WebConfiguration.java
Jetty Runner is deprecated, it is better to use an embedded Jetty instead.
Closes #3506
=> [Spring] Uses embedded Jetty instead of Jetty Runner

scala/Dockerfile, scala/akkahttp/project/build.properties, scala/http4s/project/build.properties, scala/play/project/build.properties
=> [Scala]: Scala version and sbt upgraded

go/chi/config.yaml, go/chi/go.mod
Hi @pkieltyka,
May I add you as a reviewer for `chi` ?
This project tends to be a _as fair as_ possible benchmark between frameworks.
As for now, only `req/s` is indicated, but others insights will come.
Regards,
=> [Go] modularize chi

java/micronaut/config.yaml
=> Use last gradle version

cpp/drogon/config.yaml, reviewers.yaml
Hi @an-tao,
This `PR` updates https://github.com/an-tao/drogon to v1.2.0.
Regards,
--------
May I notify you on each `drogon` update here ?
------------
Is `drogon` already (or will become in the near future) setupable via a package manager ?
=> [C++] Update drogon to v1.2.0

python/quart/config.yaml, python/quart/requirements.txt
Hi,
This `PR` updates [quart](https://pgjones.gitlab.io/quart) to **0.14**
Regards,
=> [Python] Update quart to 0.14

java/micronaut/build.gradle, java/micronaut/config.yaml
Hi,
This `PR` update [micronaut](https://micronaut.io) to 2.2
Regards,
=> [Java] Update micronaut to 2.2

java/spring-boot/config.yaml, java/spring-boot/pom.xml
Hi,
This `PR` update `spring-boot` to **2.4**
Regards,
=> [Java] Update spring-boot to 2.4

crystal/athena/config.yaml, crystal/athena/shard.yml
Hi @Blacksmoke16,
This `PR` updates `athena` to **0.12**
Regards,
------
May I notify you on each update `here` ?
=> [Crystal] Update athena to 0.12

.semaphore/semaphore.yml, lib/tasks/ci.rake, python/blacksheep/config.yaml, python/blacksheep/requirements.txt
Hi @RobertoPrevato,
This `PR` updates `blacksheep` to **0.3**
Regards,
-----
May I notify you on each update that affect `blacksheep` here ?
=> [Python] Update blacksheep to 0.3

.semaphore/semaphore.yml, python/guillotina/config.yaml, python/guillotina/requirements.txt, python/guillotina/server.py
Hi @masipcat,
I have created a `PR` based on you work.
I have add some configuration, due to **alpine** usage.
Regards,
=> [Python] Add guillotina

java/struts2/pom.xml
Hi,
This is a redo of #3574
Regards,
=> [Java] Update jetty to v11

php/hyperf/app/Kernel/FastServer.php, php/hyperf/composer.json, php/hyperf/config.yaml, php/hyperf/config/autoload/server.php, php/one-fpm/composer.json, php/one-fpm/config.yaml, php/one/composer.json, php/one/config.yaml
=> Update dependency hyperf/framework to ~2.1.0

.semaphore/semaphore.yml, rust/salvo/Cargo.toml, rust/salvo/config.yaml, rust/salvo/src/main.rs
Hi @chrislearn,
This `PR` add salvo in here.
A quick question about `dependencies` section in `Cargo.toml`. 
I can see that use use a hash-like syntax, when the other rust frameworks here is a simple string like in https://github.com/the-benchmarker/web-frameworks/blob/c82fe09f9c163bcabe47d5d19750640485dda7ac/rust/nickel/Cargo.toml#L7
What are the differences ?
Regards,
-------------- 
Closes #3656 
Closes #3652
=> [Rust] Add salvo

.semaphore/semaphore.yml, cpp/Dockerfile, cpp/nawa/CMakeLists.txt, cpp/nawa/config.ini, cpp/nawa/config.yaml, cpp/nawa/main.cpp
Hi @jatofg,
This `PR` adds `nawa` in here.
ℹ️ I have some warnings
```
CMake Warning (dev) at build/_deps/cppnetlib-src/CMakeLists.txt:8 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.
```
when using `cmake -DCMAKE_BUILD_TYPE=release ..`
I will post more info when CI passes
-----
May I notify you on each update that affects `nawa` here ?
-----
Closes #3634 
Closes #3645
=> [C++] Add nawa

fsharp/falco/config.yaml
Hi @pimbrouwers,
I've found https://www.falcoframework.com
Is this website up-to-date ?
Regards,
--------
Closes #3720
=> [F#] Update falco website

php/ubiquity/composer.json
=> [PHP] Fix ubiquity

.semaphore/semaphore.yml, java/undertow/.gitignore, java/undertow/config.yaml, java/undertow/pom.xml, java/undertow/src/main/java/the/benchmarker/Main.java
=> [Java] Add undertow

.semaphore/schedule.yml, .semaphore/semaphore.yml, java/sparkjava/.gitignore, java/sparkjava/config.yaml, java/sparkjava/pom.xml, java/sparkjava/src/main/java/the/benchmarker/Main.java
Hi @whiplash,
This a relocation of your PR #3674.
Regards,
----------
Closes #3674
=> [Java] Add spark

python/responder/requirements.txt
=> [Python] Clean responder deps

README.md, java/activej/config.yaml
=> [Java] Fix activej version

php/chubbyphp-swoole/public/index.php, php/hyperf/app/Kernel/FastServer.php, php/hyperf/config/autoload/server.php, php/imi/config/config.php, php/one/App/Config/protocol.php, php/siler-swoole/public/index.php, php/simps/app/Controller/IndexController.php, php/simps/config/servers.php, php/slim-swoole/public/index.php, php/sw-fw-less/config/server.php, php/swoft/app/bean.php, php/yii-swoole/config/server.php, reviewers.yaml
+ Set worker number to `swoole_cpu_num() * 2`
+ Disable coroutine
+ Disable logs
+ [x] chubbyphp-swoole
+ [x] hyperf
+ [x] imi
+ [x] one
+ [x] siler-swoole
+ [x] simps
+ [x] slim-swoole
+ [x] sw-fw-less
+ [x] swoft
+ [x] yii-swoole
=> Update swoole config

php/laravel/app/Http/Kernel.php, php/laravel/artisan, php/laravel/composer.json, php/laravel/config.yaml
- Upgrade to Laravel 8
- Remove default middleware for session/cookies etc
- Cache the config + routes as described in https://github.com/the-benchmarker/web-frameworks/issues/3393
Fixes https://github.com/the-benchmarker/web-frameworks/issues/3393
=> Laravel v8

php/antidot/composer.json
Fix composer version issues discussed at https://github.com/the-benchmarker/web-frameworks/issues/3804
=> [PHP] Antidot React Fix composer versions

php/driftphp/composer.json, php/driftphp/config.yaml
After last results, I implemented this small feature in the server in order to start using all available threads. Fingers crossed.
=> Improved DriftPHP performance. Added multi-thread feature.

python/masonite/config.yaml, python/masonite/requirements.txt
Reverts the-benchmarker/web-frameworks#3792
=> Revert "Update dependency masonite to v3"

.github/CODEOWNERS, .github/workflows/ci.yml, README.md
Hi @laylatichy,
This `PR` include `fatfree` in results.
Regards,
----------
@bcosca May I notify you on `fatfree` update here ?
=> Include fatfree in README

php/webman/app/controller/User.php, php/webman/composer.json, php/webman/config.yaml, php/webman/config/bootstrap.php, php/webman/config/container.php, php/webman/config/route.php, php/webman/config/server.php, php/webman/start.php, php/webman/support/Request.php, php/webman/support/Response.php, php/webman/support/bootstrap/Container.php, php/webman/support/bootstrap/Log.php, php/webman/support/helpers.php
Add [Webman](https://github.com/walkor/webman)
Webman is a high performance HTTP Service Framework for PHP based on Workerman.
=> [PHP] Add Webman

php/antidot/composer.json, php/antidot/config.yaml, php/antidot/config/config.php, php/antidot/config/services/dependencies.prod.yaml, php/antidot/public/index.php, php/antidot/router/middleware.php
I added support to run the framework using all available threads;-D. Also, I included a package that implements the application global middleware classes using promises. 
Thanks for your great work :clap::clap::clap:
=> [PHP] Antidot: Enable multi-thread feature

.github/workflows/ci.yml
Hi,
This `PR` adds authentication for docker hub.
Regards,
=> Docker hub authentication

.gitignore, .spec/route_spec.rb, README.md, README.mustache.md, crystal/Dockerfile, crystal/athena/config.yaml, crystal/athena/shard.yml, crystal/athena/src/server.cr
* Upgrade Athena to `0.13.x`
* Bump Dockerfile to use Crystal `0.36.1`
* Add new generated files to .gitignore
* Add `jq` to requirements section in README
=> Athena Upgrade

php/sunrise-router-annotations/composer.json, php/sunrise-router-annotations/config.yaml, php/sunrise-router-annotations/public/index.php, php/sunrise-router-roadrunner/worker.php, php/sunrise-router/public/index.php, rust/salvo/Cargo.toml
=> [PHP] Sunrise Router / improved code

go/webgo/go.mod
=> updated webgo to v4.1.10

README.md, crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v4.0

php/ice/config.yaml
https://github.com/the-benchmarker/web-frameworks/pull/3655#issuecomment-780432282
=> Ice, don't get from pecl until we get a stable version

php/cubex/composer.json
Optimised requirements. 
Recommended by @Bajb
=> Add packaged-polyfils to cubex

go/goyave/config.yaml, go/goyave/go.mod, go/goyave/main.go
cf. https://github.com/the-benchmarker/web-frameworks/pull/4016#pullrequestreview-600982987
=> Update Goyave to v3.7.0

README.md, rust/iron/config.yaml
See: https://github.com/iron/iron/issues/632
=> Update iron URL

cpp/drogon/config.yaml
Hi @an-tao,
This `PR` update `drogon` to the latest version.
Regards,
-------
Closes #4040
=> [C++] Update drogon to v1.4.1

.semaphore/schedule.yml, .semaphore/semaphore.yml, swift/hummingbird-framework/Package.swift, swift/hummingbird-framework/Sources/server/main.swift, swift/hummingbird-framework/config.yaml
=> Add Swift Hummingbird framework

swift/kitura-nio/Package.swift, swift/kitura/Package.swift, swift/perfect/Package.swift, swift/swifter-framework/Package.swift, swift/vapor-framework/Package.swift
=> [SWIFT] Enable cross module optimisation for Swift

python/django-ninja/requirements.txt
Hi @MajidHeydari,
Thanks for bring my attention on this.
Feel free to open a `PR` in this case, I'll guide you if needed
Regards,
----------
Closes #4050
=> wrong version range

php/laravel/config.yaml, php/laravel/config/servel.php
Hi @gregorip02,
When running `php artisan servel start`, I have the following error message 
```php
Servel 0.0.1 by Gregori Piñeres and contributors.
In Servel.php line 29:
Argument 1 passed to Servel\Servel::Servel\{closure}() must be of the type array, string given, called in /usr  
/src/app/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php on line 234 
```
Regards,
=> [PHP] Add workerman for laravel

rust/gotham/Cargo.toml, rust/gotham/config.yaml, rust/gotham/src/main.rs, rust/iron/Cargo.toml, rust/iron/src/main.rs, rust/nickel/Cargo.toml, rust/nickel/src/main.rs
As requested in #4086 
CC @waghanza
=> Update rust/gotham to 0.6 and rust 2018 edition

go/gorilla-mux/main.go
Hi @System-Glitch,
Thanks for spotting the implementation error with https://github.com/gorilla/mux.
Regards,
=> Fix 405 for gorilla/mux

r/plumber/DESCRIPTION, r/plumber/config.yaml
Hi @schloerke,
This `PR` update **plumber** in here.
May I notify you on each update that can affect `plumber` ?
Regards,
=> [R] Update plumber to v1.1

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml, r/Dockerfile
Hi,
This `PR` upgrade spider-gazelle to v4.3.
Regards,
/cc @stakach
=> [Crystal] Update spider-gazelle to v4.3

crystal/grip/config.yaml, crystal/grip/shard.yml
Hi @grkek,
This `PR` reset grip version : from **5.0** to **1.0**
Regards,
=> [Crystal] Reset grip version

cpp/drogon/config.yaml
Hi @an-tao,
This `PR` update https://github.com/an-tao/drogon to 1.5.
Regards,
=> [C++] Update drogon to 1.5

r/restrserve/DESCRIPTION, r/restrserve/config.yaml, reviewers.yaml
Hi,
This `PR` updates https://github.com/rexyai/RestRserve to **0.4**.
@dselivanov May I add you to `CODEOWNER` in order to notify you on each modification here ?
Regards,
=> [R] Update RestRserve to 0.4

nim/mike/config.yaml, nim/mike/server.nim, nim/mike/server.nimble
This supersedes  #4192  
this updates https://github.com/ire4ever1190/mike to 1.1.0 and updates the file here to reflect the new changes
=> [Nim] Update mike to 1.1

nim/Dockerfile
* Add -d:danger to remove more runtime checks
* Add link time optimisation
=> [Nim] Add more optimisations

r/httpuv/DESCRIPTION, r/httpuv/config.yaml
Hi,
This `PR` update `httpuv` to **1.6**
Regards,
PS : Feel free to check the code base / apply `r` best-practices for **production** usage @schloerke  @wch  @jcheng5
=> [R] Update httpuv to 1.6

javascript/tinyhttp/app.js, javascript/tinyhttp/config.yaml, javascript/tinyhttp/package.json
Hi @talentlessguy,
Following https://github.com/talentlessguy/tinyhttp/issues/246, this `PR` adds https://github.com/talentlessguy/tinyhttp in `here`.
Actually, this implementation is very simple, but will change in the future.
Regards,
=> [Javascript] Add tinyhttp

scala/finatra/build.sbt, scala/finatra/config.yaml
Hi,
This `PR` update https://github.com/twitter/finatra to **2.14**
Regards,
----------------
Closes #4225
=> [Scala] Update finatra to 2.14

crystal/athena/config.yaml, crystal/athena/shard.yml
Hi @Blacksmoke16,
This `PR` update https://github.com/athena-framework/athena to **0.14**
Regards,
=> [Crystal] Update athena to 0.14

.semaphore/schedule.yml, .semaphore/semaphore.yml, csharp/beetlex/Program.cs
Hi @beetlex-io,
I didn't notice that the implementation was not correct in https://github.com/the-benchmarker/web-frameworks/pull/4257 (should have checked if CI pipeline has been reconfigured).
Here is my correction.
Please feel free to recommend any `C#` usages / best-practices
Regards,
=> Fix BeetleX

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
Hi @stakach,
This `PR` update https://github.com/spider-gazelle/spider-gazelle to **4.3**
This version target `crystal` **1.0** and then will be merge in https://github.com/the-benchmarker/web-frameworks/pull/4098
Regards,
----------
Closes #4276
=> [Crystal] Update spider-gazelle to 4.3

cpp/drogon/config.yaml
Hi @an-tao,
This `PR` update https://github.com/an-tao/drogon to **1.6.0**
Regards,
=> [C++] Update drogon to 1.6

scala/Dockerfile
=> [scala]: Update Dockerfile

java/spring/config.yaml, java/spring/pom.xml
=> [Java] Update spring to 2.5

scala/finatra/build.sbt, scala/finatra/config.yaml
=> [Scal] Update finatra to 21.5 

javascript/tinyhttp/config.yaml
=> [Javascript] Fix tinyhttp version

go/mars/config.yaml
Thanks @roblillack
-------
Closes #4410
=> [Go] Fix mars

config.yaml, cpp/Dockerfile, cpp/drogon/config.yaml, cpp/evhtp/config.yaml, cpp/nawa/config.yaml
/cc @an-tao 
--------------
Closes #4413
=> [C++] Update drogon to v1.7

nim/prologue/config.yaml, nim/prologue/server.nim, nim/prologue/server.nim.cfg, nim/prologue/server.nimble
PR adds Prologue (one of the most famous nim web frameworks) to the benchmark
@xflywind agreed to add it, but I would like to review it too
=> Add Prologue

Rakefile, php/Dockerfile, php/phalcon/composer.json, php/phalcon/config.yaml
This `PR` update [phalcon](https://github.com/phalcon/cphalcon) to v5
The idea is to unblock https://github.com/the-benchmarker/web-frameworks/pull/3655
/cc @niden
=> [PHP] Update phalcon to v5.0

php/hyperf/config.yaml
https://github.com/the-benchmarker/web-frameworks/pull/3655#issuecomment-882393804
=> Fix missing ext-pcntl for hyperf

nim/jester/server.nim.cfg, nim/mike/server.nim.cfg, nim/prologue/server.nim, nim/whip/server.nim.cfg
Some frameworks perform a lot better with threads:on flag so I added separately cfg files to them. 
Also added debug=false to prologue to disable logging.
=> Add threads:on on frameworks using httpbeast & httpx

php/hamlet/composer.json, php/hamlet/config.yaml
Hi,
This `PR` update `hamlet` to v3.3
/cc @vasily-kartashov
Regards,
=> [PHP] Update hamlet to v3.3

go/apirouter/config.yaml, go/apirouter/go.mod, go/apirouter/main.go
Hi @cnotch,
This `PR` adds https://github.com/cnotch/apirouter to our benchmark.
I'm not specialized in `go` so I could find what I need to write a proper implementation\.
Feel free to correct me.
---------
Closes #4508
=> [Go] Add apirouter

java/micronaut/build.gradle, java/micronaut/config.yaml
Hi,
This `PR` upgrades https://micronaut.io to v 3.x
Regards,
----------
Closes #4579
=> [Java] Update micronaut to v3.0

crystal/kemal/config.yaml, crystal/kemal/shard.yml
Hi,
This `PR` updates https://github.com/kemalcr/kemal to **1.1**
Regards,
/cc @sdogruyol
=> [Crystal] Update kemal to v1.1

crystal/athena/config.yaml, crystal/athena/shard.yml, crystal/athena/src/server.cr
Hi @Blacksmoke16,
This `PR` updates `athena` to **0.15**
Regards,
=> [Crystal] Update athena to v0.15

go/bunrouter/config.yaml, go/bunrouter/go.mod, go/bunrouter/main.go
I've tried to follow https://github.com/go-bun/web-frameworks/blob/master/CONTRIBUTING.md, but it looks outdated...
=> [Go] Add uptrace/bunrouter

rust/rocket/src/main.rs
just return the value directly
=> [Rust] Optimize get_user handler for rocket

go/r2/main.go
Since `v0.3.0` introduced some performance optimizations, so it's best to reflect them here.
=> [Go] Improve R2

php/antidot/composer.json, php/antidot/config.yaml
Hi @waghanza, we recently updated Antidot Framework to 1.0.0 it allows us to set composer versions to "@stable" in all cases.
Thanks for your excellent work ;-D
=> [PHP] Update to Antidot Framework 1.0

javascript/spliffy/app.js, javascript/spliffy/config.yaml, javascript/spliffy/package.json, javascript/spliffy/www/index.rt.js, javascript/spliffy/www/user/$id.rt.js, javascript/spliffy/www/user/index.rt.js
=> update spliffy to 0.8.2

fsharp/websharper/config.yaml, fsharp/websharper/web.fsproj
=> [F#] Update websharper to v5.0

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
------
Closes #4870 
Closes #4377
=> [Crystal] Update spider-gazelle to v4.7

java/micronaut/config.yaml
=> [Java] Use latest gradle version for micronaut

rust/poem/Cargo.toml, rust/poem/config.yaml, rust/poem/src/main.rs
Poem is a full-featured and easy-to-use web framework with the Rust programming language.
=> [Rust] Add Poem

nim/httpbeast/config.yaml, nim/httpbeast/server.nimble
https://github.com/dom96/httpbeast
=> Update httpbeast to 0.4

php/mark/composer.json, php/mark/config.yaml, php/mark/start.php
=> Update Mark to v2.0

rust/axum/Cargo.toml, rust/axum/config.yaml, rust/axum/src/main.rs
> `axum` is a web application framework that focuses on ergonomics and modularity.
cc @davidpdrsn @jplatte
=> [Rust] Add Axum

ruby/grape/Gemfile, ruby/grape/config.yaml
Revert https://github.com/the-benchmarker/web-frameworks/pull/4963
=> [Ruby] Update grape to v1.6.1

php/webman/config/app.php
https://github.com/the-benchmarker/web-frameworks/pull/5001
=> [PHP] Webman fix warning

cpp/nawa/CMakeLists.txt, cpp/nawa/config.yaml, cpp/nawa/main.cpp
This hopefully fixes the issues with the framework. I haven't been able to test it with your testing framework, I hope it works.
=> [C++] Update nawa to v0.8.0

scala/Dockerfile
=> scala: upgrade of base image

rust/oxidy/Cargo.toml, rust/oxidy/config.yaml, rust/oxidy/src/main.rs
Added oxidy framework, please let me know if there is any changes require.
--------
Closes #5086
=> Added oxidy Rust Web Framework

cpp/drogon/config.yaml
Hi @an-tao,
This `PR` updates drogon to v1.7.5
Regards,
=> [C++] Update drogon to v1.7.5

go/aurora/config.yaml, go/aurora/go.mod, go/aurora/main.go
Hi @aurora-go,
This `PR` adds `aurora` in here.
However, not sure about how to get `id` URL param in `/user/{id}` 
Also, may I notify you on each update (of `aurora`) in here ?
-------
Closes #5168
=> add aurora

php/framework-x/app.php, php/framework-x/composer.json, php/framework-x/config.yaml
Hi everyone!
This `PR` adds `Framework X` in here.
Website: https://framework-x.org/
Repository: https://github.com/clue/framework-x/
Maintainer: [Christian Lück](https://github.com/clue)
=> [PHP] Add Framework X

php/antidot/config.yaml, php/driftphp/config.yaml, php/imi-workerman/config.yaml, php/mixphp-workerman/config.yaml, php/slim-roadrunner/config.yaml, php/sunrise-router-roadrunner/config.yaml, php/sw-fw-less/config.yaml, php/tower/config.yaml, php/webman/config.yaml, php/workerman/config.yaml
Hi,
This `PR` removes the workaround introduced in https://github.com/the-benchmarker/web-frameworks/pull/5049 regarding `workerman`
Regards,
--------
Closes #5065
=> [PHP] Remove unnecessary compilation options

r/ambiorix/DESCRIPTION, r/ambiorix/app.R, r/ambiorix/config.yaml
Added the ambiorix framework (R language)
=> [R] add ambiorix framework

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v4.8

go/nanomux/config.yaml, go/nanomux/go.mod, go/nanomux/main.go
Added the Go language router NanoMux.
=> Add NanoMux

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v5.1

ruby/hanami/Gemfile, ruby/hanami/config.ru, ruby/hanami/config.yaml, ruby/hanami/config/app.rb, ruby/hanami/config/routes.rb
=> Add Hanami 2.0.0.beta

javascript/pxe/app.js, javascript/pxe/config.yaml, javascript/pxe/package.json
cc @aquapi 
--------
Closes #5499
=> [Javascript] Add pxe

go/flamego/config.yaml, go/flamego/go.mod, go/flamego/main.go
Fix https://github.com/the-benchmarker/web-frameworks/issues/5503
=> [Go] Add Flamego

javascript/pxe/app.js
=> [Javascript] Optimize PXE

php/chubbyphp-roadrunner/config.yaml, php/chubbyphp-workerman/config.yaml
https://github.com/the-benchmarker/web-frameworks/pull/5087
=> remove workaround

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v5.2

cpp/drogon/config.yaml
=> [C++] Update drogon to v1.8 

javascript/pxe/app.js, javascript/pxe/config.yaml, javascript/pxe/package.json
Just change PXE again.  I make some mistakes while coding that decrease PXE performance. @waghanza
=> Update PXE code

php/chubbyphp-swoole/config.yaml
=> [PHP] Use swoole v5 for chubbyphp

java/Dockerfile, java/act/config.yaml, java/activej/pom.xml, java/config.yaml, java/jersey-grizzly2/config.yaml, java/jersey3-grizzly2/config.yaml, java/jooby/pom.xml, java/light-4j/config.yaml, java/micronaut/config.yaml, java/quarkus/config.yaml, java/quarkus/pom.xml, java/restheart/config.yaml, java/restheart/pom.xml, java/spark/pom.xml, java/spring/config.yaml, java/struts2/pom.xml, java/undertow/config.yaml, java/undertow/pom.xml, java/vertx/config.yaml, java/vertx/pom.xml, java/vertx4web/config.yaml, java/vertx4web/pom.xml
Not sure all frameworks are ready @whiplash
Let see ...
----
Close #5642
=> [Java] Upgrade to v17

javascript/chubbyts-uwebsockets/app.ts, javascript/chubbyts-uwebsockets/config.yaml, javascript/chubbyts-uwebsockets/package.json, javascript/chubbyts/app.ts, javascript/chubbyts/config.yaml, javascript/chubbyts/package.json
IMPORTANT: 1.6.0 is broken, so 1.6.1 is min requirement
=> chubbyts-framework upgrade

javascript/fyrejet-uwebsockets/package.json, javascript/sifrr/package.json
Hi,
`uWebSocket` has been released
https://github.com/uNetworking/uWebSockets.js/releases/tag/v20.11.0
Time to update
cc @aadityataparia @schamberg97
=> [Javascript] Update uWebSocket to 20.11

go/aurora/config.yaml, go/aurora/go.mod, go/aurora/main.go, go/aurora/server.go
aurora 升级到 v1.3.2 优化了RESTFul 参数解析
=> Aurora update v1.3.2

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v5.4

php/phalcon/composer.json, php/phalcon/config.yaml
=> [PHP] Update phalcon to 5.1

rust/graphul/Cargo.toml, rust/graphul/config.yaml, rust/graphul/src/main.rs
An Express-inspired web framework written in Rust
https://graphul-rs.github.io/
=> add graphul ( Rust )

nim/prologue/config.yaml, nim/prologue/server.nimble
=> [Nim] Update prologue to v0.6

php/nano/composer.json, php/nano/config.yaml, php/nano/index.php
=> chore: bump nano to v4

php/lemon/composer.json, php/lemon/config.yaml, php/lemon/public/index.php
This PR adds Lemon Microframework for PHP.
=> [PHP] Added Lemon Microframework

fsharp/websharper/config.yaml, fsharp/websharper/web.fsproj
=> [F#] Update websharper to 6.1

php/hyperf/app/Kernel/FastServer.php, php/hyperf/composer.json, php/hyperf/config.yaml, php/hyperf/config/autoload/server.php
refer https://github.com/the-benchmarker/web-frameworks/pull/6034
=> Upgrade hyperf framework to v3.0

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v5.5

crystal/toro/shard.yml, crystal/toro/src/toro.cr
=> [Crystal] Update toro to v0.5

php/unic/composer.json, php/unic/config.yaml, php/unic/public/index.php
Added latest version of unic framework and used swoole server.
=> Latest version of unic framework

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v5.6

javascript/routejs-uwebsocket/app.js, javascript/routejs-uwebsocket/config.yaml, javascript/routejs-uwebsocket/package.json
Added uWebSocketjs server in routejs
=> Added uWebSocketjs server in routejs

crystal/lucky/config.yaml, crystal/lucky/config/setup.cr, crystal/lucky/shard.yml, crystal/lucky/src/actions/api_action.cr, crystal/lucky/src/lucky.cr
I think this is all I need? Let me know if I'm missing something.
=> Adding in Lucky Framework for Crystal

php/kuiper/composer.json, php/kuiper/config.yaml, php/kuiper/src/config.php, php/kuiper/src/container.php, php/kuiper/src/controller/IndexController.php, php/kuiper/src/index.php
Kuiper is a simple php framework, document by https://kuiper-framework.github.io/en/
=> [PHP] Added kuiper framework

javascript/nhttp/app.js, javascript/nhttp/config.yaml, javascript/nhttp/package.json
Add JS framework [nhttp](https://nhttp.deno.dev). ported to Node using [Undici](https://github.com/nodejs/undici)
=> [Javascript]: Add nhttp

rust/actix/Cargo.toml, rust/axum/Cargo.toml, rust/gotham/Cargo.toml, rust/graphul/Cargo.toml, rust/iron/Cargo.toml, rust/nickel/Cargo.toml, rust/oxidy/Cargo.toml, rust/poem/Cargo.toml, rust/rocket/Cargo.toml, rust/salvo/Cargo.toml, rust/tide/Cargo.toml, rust/viz/Cargo.toml, rust/warp/Cargo.toml
=> Disable debug for all rust frameworks

nim/happyx/config.yaml, nim/happyx/server.nim, nim/happyx/server.nimble
`happyx` version changed to `0.20.0`
=> update happyx version and happyx server 👀

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml, crystal/spider-gazelle/src/controllers/user.cr, crystal/spider-gazelle/src/controllers/welcome.cr
=> [Crystal] Update spider-gazelle to v6

nim/Dockerfile, nim/happyx/config.yaml, nim/happyx/server.nimble
=> Update `nim/happyx` to `1.0.0` 👀

javascript/fastify/app.js
Hello,
just updated the Fastify bench to fix the deprecation (and get 1 req/sec more 😄)
=> chore: fix fastify deprecation

javascript/stricjs/app.ts, javascript/stricjs/package.json
=> Update Stric (and Bun to 0.6.9)

kotlin/kooby/build.gradle, kotlin/kooby/src/main/kotlin/benchmark/App.kt
- few package renames + new dependency for kotlin
=> jooby: upgrade kotlin version

nim/guildenstern/server.nim
=> Update GuildenStern server.nim

nim/happyx/config.yaml, nim/happyx/server.nim, nim/happyx/server.nimble
=> Update `nim/happyx` version

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v7.1

d/serverino/.gitignore, d/serverino/config.yaml, d/serverino/dub.json, d/serverino/source/app.d
Simple server for fast testing
Tests passed locally: https://github.com/cyrusmsk/web-frameworks/actions/runs/5695345431
Spoke with author in Discord. But probably it will be better if he review the code too.
Ciao @trikko . Are you fine to add Serverino to this repo? And if you can propose better options to the code -  will be highly appreciated. Thanks
=> Added serverino http server

crystal/amber/config.yaml, crystal/amber/shard.yml
=> [Crystal] Update amber to v1.4

nim/mike/config.yaml, nim/mike/server.nimble
Updates mike
Fixes CI issue in #6568
=> [Nim] Update mike to 1.3

v/Dockerfile, v/vex/config.yaml, v/vex/main.v
Easy-to-use, modular web framework for [V](https://vlang.io/).
site: https://nedpals.github.io/vex/
source: https://github.com/nedpals/vex
=> v | added vex

v/pico/config.yaml, v/pico/main.v
site: https://github.com/vlang/v/tree/master/vlib/picoev
=> v | added pico

javascript/stricjs/app.ts, javascript/stricjs/package.json
If the base URL does not match you can change it to the URL that you are benchmarking
=> Update Stric to 4.0.9

clojure/pedestal/.gitignore, clojure/pedestal/config.yaml, clojure/pedestal/project.clj, clojure/pedestal/src/the_benchmarker_pedestal/server.clj, clojure/pedestal/src/the_benchmarker_pedestal/service.clj
Add [Pedestal](https://github.com/pedestal/pedestal) web framework.
| HTTP   | Route       | Status code | Response body         | Done? |
| ------ | ----------- | ----------- | --------------------- | ------- |
| `GET`  | `/`         | `200`       | **Empty**             | ✅ |
| `GET`  | `/user/:id` | `200`       | **id** given as param | ✅ |
| `POST` | `/user`     | `200`       | **Empty** | ✅ |
=> Add clojure Pedestal web framework

rust/summer-boot/Cargo.toml, rust/summer-boot/config.yaml, rust/summer-boot/src/main.rs, rust/summer-boot/src/resources/application-test.yml, rust/summer-boot/src/resources/application.yml
CC [issues 72](https://github.com/wansenai/summer-boot/issues/72).
=> Add a web framework for the Rust language

php/aplus-app/App.php, php/aplus-app/app/Controllers/Home.php, php/aplus-app/app/Controllers/User.php, php/aplus-app/boot/app.php, php/aplus-app/boot/constants.php, php/aplus-app/boot/helpers.php, php/aplus-app/boot/init.php, php/aplus-app/boot/routes.php, php/aplus-app/composer.json, php/aplus-app/config.yaml, php/aplus-app/config/antiCsrf.php, php/aplus-app/config/autoloader.php, php/aplus-app/config/cache.php, php/aplus-app/config/console.php, php/aplus-app/config/database.php, php/aplus-app/config/debugger.php, php/aplus-app/config/exceptionHandler.php, php/aplus-app/config/language.php, php/aplus-app/config/locator.php, php/aplus-app/config/logger.php, php/aplus-app/config/mailer.php, php/aplus-app/config/migrator.php, php/aplus-app/config/request.php, php/aplus-app/config/response.php, php/aplus-app/config/router.php, php/aplus-app/config/session.php, php/aplus-app/config/validation.php, php/aplus-app/config/view.php, php/aplus-app/public/index.php
Adding a new framework: [Aplus App](https://github.com/aplus-framework/app).
Thank you!
=> Add Aplus App

php/aplus-one/composer.json, php/aplus-one/config.yaml, php/aplus-one/public/index.php
Add [Aplus One](https://github.com/aplus-framework/one).
=> Add Aplus One

java/jooby/config.yaml, java/jooby/pom.xml, kotlin/kooby/build.gradle, kotlin/kooby/config.yaml
- move from undertow to netty web server
=> jooby: netty implementation

javascript/node.Dockerfile
=> [Javascript] Use npm 10

javascript/ditsmod/.gitignore, javascript/ditsmod/config.yaml, javascript/ditsmod/package.json, javascript/ditsmod/src/app/app.module.ts, javascript/ditsmod/src/app/hello-world.controller.ts, javascript/ditsmod/src/main.ts, javascript/ditsmod/tsconfig.json
Please add a new framework for benchmarks - [Ditsmod](https://ditsmod.github.io/en/)
=> Please add a new framework for benchmarks - Ditsmod.

perl/kossy/config.yaml, perl/kossy/cpanfile, perl/kossy/d2app.psgi
Please add micro framework Kossy.
=> [Perl] Add Kossy

javascript/bunicorn/app.ts, javascript/bunicorn/config.yaml, javascript/bunicorn/package.json
Hello, I wanted to add the new framework that is running on top of Bun. I was not able to test locally because I was not able to run it on Apple Silicon. I know, the framework yet does not have a documentation but I am creating it right now and wanted to see how it performs and see it on https://web-frameworks-benchmark.netlify.app. Thanks!
=> feat(javascript): add Bunicorn

javascript/fiber/app.js, javascript/fiber/config.yaml, javascript/fiber/package.json
Please add a new JavaScript framework: [Fiber](https://github.com/ionited/fiber)
=> feat(javascript): add Fiber

javascript/bunicorn/app.ts, javascript/bunicorn/config.yaml, javascript/bunicorn/package.json
Hello, I updated the way to listen the requests, which also increases performance, so I wanted to open a new pull requests. Thanks!
=> [UPDATE] - Add the new listen API for Bunicorn

php/bearframework/composer.json, php/bearframework/config.yaml
Thanks @ivopetkov
Related to https://github.com/bearframework/bearframework/issues/6#issuecomment-1768524446
=> [PHP] Use 8.2 for bearframework

crystal/lucky/config.yaml, crystal/lucky/shard.yml
Hi @jwoertink,
I can see that lucky has been updated 🎉 
https://github.com/luckyframework/lucky/releases/tag/v1.1.0
Thanks,
=> [Crystal] Update Lucky to v1.1

cpp/drogon/config.yaml
Hi @an-tao,
I've seen that drogon has been updated 🎉 
https://github.com/drogonframework/drogon/releases/tag/v1.9.0
Do you (or anywone) manage to add drogon on conan ?
Regards,
=> [C++] Update drogon to v1.9

go/hertz/main.go
I found the configuration of the current hertz code too cumbersome compared to fiber, so I chose to update hertz to mimic the fiber code.
=> chore: update hertz config

javascript/spliffy/package.json
fixes support for node 20 and correctly corks things (at least, probably closer to correctly)
=> bump spliffy to latest

csharp/config.yaml
=> [C#] Language version

fsharp/config.yaml
=> Set F# version

crystal/spider-gazelle/config.yaml, crystal/spider-gazelle/shard.yml
=> [Crystal] Update spider-gazelle to v7.3

clojure/Dockerfile, clojure/donkey/config.yaml, clojure/luminus/config.yaml, clojure/pedestal/config.yaml, java/Dockerfile, java/act/config.yaml, java/activej/pom.xml, java/blade/config.yaml, java/blade/pom.xml, java/blade/src/main/java/com/example/Application.java, java/blade/src/main/resources/application.properties, java/blade/src/resources/application.properties, java/config.yaml, java/javalin/pom.xml, java/jooby/pom.xml, java/light-4j/pom.xml, java/micronaut/config.yaml, java/quarkus/pom.xml, java/rapidoid/pom.xml, java/restheart/pom.xml, java/spark/pom.xml, java/spring-webflux/pom.xml, java/spring/pom.xml, java/struts2/pom.xml, java/undertow/pom.xml, java/vertx/pom.xml, java/vertx4web/pom.xml
=> [JVM] Use JDK 21

java/spring/src/main/resources/application.properties
The coolest feature of Java21 and SpringBoot 3.2 is Virutal Thread, so I want to include it!
=> enable virtual thread mode.

cpp/drogon/config.yaml
=> [C++] Update drogon to v1.9.1

d/Dockerfile, d/cgi/dub.json, d/handy/config.yaml, d/handy/dub.json
Update some frameworks version and version of compiler
=> [D] Version update

nim/basolato/basolato.nimble, nim/basolato/config.yaml
=> [Nim] Update basolato to 0.15

d/cgi/config.yaml, d/cgi/dub.json, d/handy/config.yaml, d/handy/dub.json, d/handy/source/app.d, d/serverino/dub.json
For CGI and Serverino just bump the version. For Handy - update the code with new functionality of PathHandler which is a recommended way from web-site
=> [D] update libraries versions

v/x.vweb/config.yaml
=> fix: xvweb

javascript/yume-server/package.json
Hey, I made some performance tweaks on the yume-server.
Off topic: If you don't mind, could you please include it in the next release? https://web-frameworks-benchmark.netlify.app/result?l=javascript
=> [Javascript] Update yume-server to 0.0.4

d/handy/config.yaml, d/handy/dub.json, d/handy/source/app.d
Removed shared and websockets are now disabled by default
=> [D] handy update version - fix building

javascript/elysia/app.ts
I refactored the elysia example app to reflect the intended way of writing elysia apps, which is by using a builder pattern.
See the [elysia docs](https://elysiajs.com/at-glance.html).
=> chore: [Elysia] refactored to builder-pattern

javascript/adonisjs6-http/app.js, javascript/adonisjs6-http/config.yaml, javascript/adonisjs6-http/package.json
Hey there! 👋🏻 
This PR adds another benchmark to test only the HTTP server of AdonisJS 6.
=> feat(adonis): add http server only

javascript/blaze/app.js, javascript/blaze/config.yaml, javascript/blaze/package.json, javascript/blaze/services/core.js, javascript/blaze/services/user.js
Add hono event driven framework, blaze, to the benchmark
=> [JavaScript] add blaze

julia/config.yaml, julia/oxygen/Manifest.toml, julia/oxygen/Project.toml, julia/oxygen/config.yaml, julia/oxygen/deps.jl, julia/oxygen/server.jl
Adding [Oxygen](https://github.com/OxygenFramework/Oxygen.jl) to the benchmark. I let the same structure as [Merly](https://github.com/neomatrixcode/Merly.jl)
------------
Closes #6736
=> Adding Julia Oxygen

d/vibed/dub.json, d/vibed/source/app.d
=> [D] Vibe.d update

nim/happyx/config.yaml
Local testing - opt: speed option has the effect of improving running speed.
=> Optimize compilation

nim/config.yaml
Optimize compilation to improve program efficiency.
=> Update Compilation switch

d/serverino/dub.json
=> [D] Update dub.json

python/config.yaml, python/django/config.yaml
- gunicorn: warning -> critical
- uvicorn: info -> critical
- django config.yaml refactory
=> reduced log level for gunicorn/uvicorn

.gitignore, python/config.yaml, python/django/config.yaml, python/fastapi/config.yaml, python/flask/config.yaml, python/litestar/config.yaml
https://github.com/emmett-framework/granian
=> python: add granian http server

d/Dockerfile, d/cgi/config.yaml, d/cgi/dub.json, d/config.yaml, d/lighttp/dub.json, d/serverino/dub.json, d/serverino/source/app.d, d/vibed/dub.json
Docker image changed from Debian to Ubuntu.
For all solutions LTO was removed
Bumped several versions for compilers
=> [D] Updates

ruby/config.yaml, ruby/rage/Gemfile, ruby/rage/Rakefile, ruby/rage/app/controllers/application_controller.rb, ruby/rage/config.ru, ruby/rage/config.yaml, ruby/rage/config/application.rb, ruby/rage/config/environments/production.rb, ruby/rage/config/routes.rb
Add https://github.com/rage-rb/rage.
=> Add rage-rb

java/restheart/config.yaml, java/restheart/etc/conf-overrides.yml, java/restheart/pom.xml
=> :arrow_up: Upgrade RESTHeart to v8.0.0-beta

rust/ohkami/Cargo.toml, rust/ohkami/config.yaml, rust/ohkami/src/main.rs
https://github.com/kana-rus/ohkami
=> add rust framework: ohkami

go/web/config.yaml, go/web/go.mod, go/web/main.go
This is still in early development but I can commit to keeping the code here up to date in case the API changes.
=> Add go framework: web

javascript/vixeny-bun/app.ts, javascript/vixeny-bun/cluster.ts, javascript/vixeny-bun/config.yaml, javascript/vixeny-bun/package.json, javascript/vixeny-deno/app.ts, javascript/vixeny-deno/config.yaml, javascript/vixeny-deno/package.json
Adding vixeny, a purely functional and agnostic framework
=> [JavaScript] Adding vixeny

go/go-zero/config.yaml, go/go-zero/go.mod, go/go-zero/main.go
=> [Go] Add go-zero

Rakefile, java/Dockerfile, java/act/config.yaml, java/act/pom.xml, java/activej/pom.xml, java/armeria/pom.xml, java/blade/config.yaml, java/blade/pom.xml, java/config.yaml, java/helidon-se/pom.xml, java/javalin/pom.xml, java/jersey-grizzly2/pom.xml, java/jersey3-grizzly2/pom.xml, java/jooby/pom.xml, java/light-4j/pom.xml, java/micronaut/config.yaml, java/quarkus/pom.xml, java/spark/pom.xml, java/spring-webflux/pom.xml, java/spring/pom.xml, java/struts2/pom.xml, java/undertow/pom.xml, java/vertx/pom.xml, java/vertx4web/pom.xml
=> [Java] Homonize maven compiler version

javascript/vixeny-bun/app.ts, javascript/vixeny-deno/app.ts
🥳 
I want to see the perf of this girl!
=> Adding POST 

python/bottle/config.yaml
=> [Python] Use gunicorn for bottle

nim/caprese/config.yaml, nim/caprese/server.nim, nim/caprese/server.nimble
Hello,
Please add https://github.com/zenywallet/caprese
=> [Nim] Add caprese

java/quarkus/pom.xml, java/quarkus/src/main/java/yolo/BenchmarkResource.java
to test the real power of Quarkus it should in reactive mode
=> apply  Quarkus reactive mode

swift/flying-fox/Package.swift, swift/flying-fox/Sources/server/Server.swift, swift/flying-fox/config.yaml
Adding https://github.com/swhitty/FlyingFox
=> Add swift flying fox

javascript/fastify-bun/app.ts, javascript/fastify-bun/cluster.ts, javascript/fastify-bun/config.yaml, javascript/fastify-bun/package.json
`fastify` as another popular npm package added for bun environment.
=> Fastify Bun added

javascript/oak-bun/app.ts, javascript/oak-bun/config.yaml, javascript/oak-bun/package.json, javascript/oak-deno/app.ts, javascript/oak-deno/config.yaml, javascript/oak-deno/package.json
=> add oak support

ruby/rails-api/config/secrets.yml, ruby/rails/config/secrets.yml
Secrets are no longer supported in Rails 8:
https://github.com/rails/rails/commit/0c76f17f2dbf0d7ad90c890e6f334743cacce41f
=> Remove secrets.yml

rust/axum/src/main.rs
=> Fix Axum benchmark

javascript/vixeny-bun/app.ts, javascript/vixeny-bun/package.json, javascript/vixeny-deno/app.ts, javascript/vixeny-deno/package.json
Sorry for that, skill issues. It should be working now, also I locked the version so it should give any problems in the future!
=> updating vixeny to 0.1.53

ruby/config.yaml
As requested by: https://github.com/the-benchmarker/web-frameworks/pull/8077#pullrequestreview-2522473290
=> Update Ruby version in ruby/config.yaml

java/struts2/config.yaml, java/struts2/pom.xml, java/struts2/src/main/webapp/WEB-INF/web.xml
Upgrades the example app to use the latest Apache Struts 7 and JakartaEE 10
=> Upgrades to Struts 7 and JakartaEE

rust/axum/src/main.rs, rust/hyper/Cargo.toml, rust/hyper/config.yaml, rust/hyper/src/main.rs
A protective and efficient HTTP library for all.
https://hyper.rs/
=> feat: new framework 'hyper'

go/poteto/config.yaml
On Poteto for goLang
- CHANGE: website
- CHANGE: version
=> CHANGE: website & version

javascript/ditsmod-bun/package.json, javascript/ditsmod-bun/src/app/hello-world.controller.ts, javascript/ditsmod/package.json, javascript/ditsmod/src/app/hello-world.controller.ts
In this PR, I fix the framework version so the package manager doesn't install a higher version. It is better to do this before the release of a stable version.
=> chore(JavaScript/ditsmod): upgrade to v3.0.0-alpha.3 and fix deps

rust/rama/Cargo.toml, rust/rama/config.yaml, rust/rama/src/main.rs
https://github.com/plabayo/rama/
modular service framework to move and transform network packets
This is in relation to issue https://github.com/plabayo/rama/issues/398 that is being tracked on Rama
=> feat: new framework "rama"

crystal/grip/src/server.cr
Set it to HTTP handler only so the rest can be ignored.
=> Update Grip for more performance

go/web/config.yaml, go/web/go.mod, go/web/main.go
Hi,
is `data.json` updated automatically?
I can add it to the commit if needed.
=> update dependency go/web

php/flight/composer.json, php/flight/config.yaml, php/flight/public/index.php
Adding Flight PHP to be added to the benchmark.
https://docs.flightphp.com
https://github.com/flightphp/core
=> Added Flight Framework for PHP

rust/micro-web/config.yaml
=> rust: fix micro-web website config

fsharp/oxpecker/Program.fs, fsharp/oxpecker/config.yaml, fsharp/oxpecker/web.fsproj
Adding Oxpecker to the F# options.
=> feat(fsharp): add Oxpecker sample

python/lihil/config.yaml, python/lihil/pyproject.toml, python/lihil/server.py
Hi there:
I would like to add my web framework  [lihil](https://lihil.cc/lihil/) to the benchmarks.
Let me know if there is anything needs to be fixed!
=> feat: add lihil

fsharp/config.yaml
Change F# language version to latest for framework version 9.0, which is 9.
=> fix(version): fsharp

kotlin/ktor/src/main/resources/logback.xml
- Less spammy logger should improve performance
=> Update logger to be less spammy

rust/rama/Cargo.toml, rust/rama/config.yaml, rust/rama/src/main.rs
- rust edition 2024
- rama version 0.2.0-alpha.13
=> chore(version): update rama to latest edition and framework version

rust/micro-web/Cargo.toml, rust/micro-web/config.yaml, rust/micro-web/src/main.rs
update rust web framework micro-web from alpha to 0.1.
=> Update Rust crate micro-web to 0.1

data.json, rust/rama/Cargo.toml, rust/rama/config.yaml
rama 0.2 anouncement:
<https://github.com/plabayo/rama/discussions/544>
=> bump rama to 0.2

python/robyn/config.yaml, python/robyn/pyproject.toml
Tried updating robyn to latest 0.69
Fix #8456
=> chore(deps): update robyn version to 0.69

julia/mongoose/Project.toml, julia/mongoose/config.yaml, julia/mongoose/deps.jl, julia/mongoose/server.jl
=> Adding Julia Mongoose

python/lihil/server.py
refactor code as Lihil is no longer generic and thus ont subscriptable
=> fix(lihil): Update source code in server.py

java/jooby/config.yaml, java/jooby/pom.xml, java/jooby/src/main/java/benchmark/App.java, kotlin/jooby/build.gradle, kotlin/jooby/config.yaml, kotlin/jooby/src/main/kotlin/benchmark/App.kt
=> jooby: 4.0

rust/silent/src/main.rs
=> fix(silent): change port to 3000

javascript/chubbyts-uwebsockets/.gitignore, javascript/chubbyts-uwebsockets/package.json, javascript/chubbyts/app.ts, javascript/chubbyts/package.json
@waghanza answer to: https://github.com/the-benchmarker/web-frameworks/pull/8646#issuecomment-3263576072
=> chubbyts fixes

rust/micro-web/Cargo.toml, rust/micro-web/config.yaml, rust/micro-web/src/main.rs
upgrade rust  micro-web from 0.2 to 0.3
=> Update rust micro-web from 0.2 to 0.3
